--E escuela
--V videoproyector
--P prestamo
--A accesorio
--REP reportes
CREATE TABLE E_DEPARTAMENTOS(
ID_DEPARTAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(40) NOT NULL,
ABBREV VARCHAR(15) NOT NULL,
ENCARGADO VARCHAR(50) NOT NULL,
CREADO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ACTUALIZADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE E_PROFESORES(
ID_PROFESOR VARCHAR(12) NOT NULL PRIMARY KEY,
ID_DEPARTAMENTO INT NOT NULL ,
NOMBRE VARCHAR(25) NOT NULL,
A_PATERNO VARCHAR(25) NOT NULL,
A_MATERNO VARCHAR(25) NOT NULL,
ADEUDO BOOLEAN DEFAULT FALSE,
ESTATUS BOOLEAN DEFAULT TRUE,
CREADO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ACTUALIZADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE E_AULAS(
ID_AULA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(25) NOT NULL,
ESTATUS BOOLEAN DEFAULT TRUE,
CREADO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ACTUALIZADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE E_USUARIOS(
ID_USUARIO VARCHAR(15) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
A_PATERNO VARCHAR(15) NOT NULL,
A_MATERNO VARCHAR(15) NOT NULL,
PASSWORD VARCHAR(60) NOT NULL,
ADMINDR BOOLEAN DEFAULT FALSE,
DISPONIBLE BOOLEAN DEFAULT TRUE,
CREADO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ACTUALIZADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE E_VIDEOPROYECTORES(
ID_VIDEOPROYECTOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(15) NOT NULL,
MARCA VARCHAR(15) NOT NULL,
MODELO VARCHAR(20) NOT NULL,
NO_SERIE VARCHAR(20) NOT NULL,
ACCESORIOS ARRAY,
CREADO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ACTUALIZADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE E_PRESTAMOS(
ID_PRESTAMO BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_SALIDA VARCHAR(15) NOT NULL,
ID_ENTRADA VARCHAR(15),
ID_VIDEOPROYECTOR INT NOT NULL,
ID_PROFESOR VARCHAR(12) NOT NULL,
ID_AULA INT NOT NULL,
ESTATUS BOOLEAN DEFAULT TRUE,                       --CICLO DE PRESTAMO Y DEVOLUCION
ESTATUS_DEVOLUCION BOOLEAN NOT NULL DEFAULT TRUE,   --INDICADOR DE DEVOLUCION SIN PROBLEMAS / CON PROBLEMAS EN EL PROYECTOR
ID_REPORTE_VIDEOPROYECTOR INT(10) DEFAULT NULL,     --REPORTE DE REFERENCIA SOBRE EL PROBLEMA CON PROYECTOR
CREADO DATETIME DEFAULT CURRENT_TIMESTAMP,
ACTUALIZADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE E_REP_VIDEOPROYECTORES(
ID_REPORTE_VIDEOPROYECTOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_VIDEOPROYECTOR INT NOT NULL,
ID_PROFESOR VARCHAR(12) NOT NULL,
TITULO VARCHAR(50) NOT NULL,
NOMBRE_ENCARGADO VARCHAR(60) NOT NULL,
AREA VARCHAR(60) NOT NULL,
DEPTO_REPARADOR VARCHAR(40) NOT NULL,
IMPREVISTO VARCHAR(20) NOT NULL,
DETALLES CLOB NOT NULL,
CREADO DATETIME DEFAULT CURRENT_TIMESTAMP,
ACTUALIZADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE E_REP_ARTICULOS( --E_REP_ACCESORIOS
ID_REPORTE_ARTICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT, --ID_REPORTE_ACCESORIO
ID_PROFESOR VARCHAR(12) NOT NULL,
TITULO VARCHAR(50),
DETALLES CLOB,
RESOLUCION CLOB,
ESTATUS BOOLEAN DEFAULT TRUE,  -- INDICA UN REPORTE ACTIVO CUANDO SE CREA, UNA VEZ EL ADMIN ACTUALIZA EL REPORTE, ESTÉ REGISTRO LIBERA AL DOCENTE
CREADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE EREPA_ARTICULOS( --EREPA_ACCESORIOS
ID_EREPA_ARTICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,--ID_EREPA_ACCESORIO
ID_ARTICULO INT NOT NULL, --ID_ACCESORIO
ID_REPORTE_ARTICULO INT NOT NULL,--ID_REPORTE_ACCESORIO
CREADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE E_ARTICULOS(--E_ACCESORIOS
ID_ARTICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT, --ID_ACCESORIO 
NOMBRE VARCHAR(20),
EXISTENCIAS INT,
--DISPONIBLE INT,
DESCRIPCION CLOB);

CREATE TABLE EPV_ARTICULOS( --EPV_ACCESORIOS
ID_EPV_ARTICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT, --ID_EPV_ACCESORIO
ID_ARTICULO INT NOT NULL, --ID_ACCESORIO
ID_PRESTAMO BIGINT NOT NULL,
ESTATUS BOOLEAN DEFAULT TRUE, --INDICA QUE UN ARTICULO NO FUE REPORTADO
CREADO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE EV_HORASSERVICIO(
ID_HORAS_SERVICIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_VIDEOPROYECTOR INT NOT NULL,
TOTAL INT DEFAULT 0,
MES INT DEFAULT 0,
SEMESTRE INT DEFAULT 0);

CREATE TABLE EV_ESTATUS(
ID_ESTATUS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_VIDEOPROYECTOR INT NOT NULL,
NOMBRE VARCHAR(15),
DISPONIBILIDAD BOOLEAN DEFAULT TRUE);

CREATE TABLE E_LOG_MOVIMIENTOS( 
ID_LOG INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO VARCHAR(15) NOT NULL,
ACCION CHAR(6),
TABLA VARCHAR(40),
FECHA DATETIME DEFAULT CURRENT_TIMESTAMP);

/* FOREIGN KEYS */

  ALTER TABLE E_PROFESORES
  ADD CONSTRAINT PROFESORES_FK_DEPARTAMENTO
  FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES E_DEPARTAMENTOS(ID_DEPARTAMENTO)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE E_PRESTAMOS
  ADD CONSTRAINT PRESTAMOS_FK_USUARIO_REGISTRA_SALIDA
  FOREIGN KEY (ID_SALIDA) REFERENCES E_USUARIOS(ID_USUARIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE E_PRESTAMOS
  ADD CONSTRAINT PRESTAMOS_FK_USUARIO_REGISTRA_ENTRADA
  FOREIGN KEY (ID_ENTRADA) REFERENCES E_USUARIOS(ID_USUARIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE E_PRESTAMOS
  ADD CONSTRAINT PRESTAMOS_FK_VIDEOPROYECTOR
  FOREIGN KEY (ID_VIDEOPROYECTOR)
  REFERENCES E_VIDEOPROYECTORES(ID_VIDEOPROYECTOR)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE E_PRESTAMOS
  ADD CONSTRAINT PRESTAMOS_FK_PROFESOR
  FOREIGN KEY (ID_PROFESOR)
  REFERENCES E_PROFESORES(ID_PROFESOR)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE E_PRESTAMOS
  ADD CONSTRAINT PRESTAMOS_FK_AULA
  FOREIGN KEY (ID_AULA)
  REFERENCES E_AULAS(ID_AULA)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE E_REP_VIDEOPROYECTORES
  ADD CONSTRAINT REPORTES_VID_FK_VIDEOPROYECTOR
  FOREIGN KEY (ID_VIDEOPROYECTOR)
  REFERENCES E_VIDEOPROYECTORES(ID_VIDEOPROYECTOR)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE EREPA_ARTICULOS --EREPA_ACCESORIOS
  ADD CONSTRAINT ARTICULOS_FK_E_REP_A --ACCESORIOS_FK_E_REP_A
  FOREIGN KEY (ID_ARTICULO) --ID_ACCESORIO
  REFERENCES E_ARTICULOS(ID_ARTICULO) --E_ACCESORIOS(ID_ACCESORIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE EREPA_ARTICULOS --EREPA_ACCESORIOS
  ADD CONSTRAINT REPORTE_A_FK_E_REP_A
  FOREIGN KEY (ID_REPORTE_ARTICULO)--ID_REPORTE_ACCESORIO
  REFERENCES E_REP_ARTICULOS(ID_REPORTE_ARTICULO)--E_REP_ACCESORIOS(ID_REPORTE_ACCESORIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE E_REP_ARTICULOS --E_REP_ACCESORIOS
  ADD CONSTRAINT REPORTES_ART_FK_PROFESOR
  FOREIGN KEY (ID_PROFESOR)
  REFERENCES E_PROFESORES(ID_PROFESOR)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE EPV_ARTICULOS --EPV_ACCESORIOS
  ADD CONSTRAINT ARTICULOS_FK_E_P_V_ARTICULOS --ACCESORIOS_FK_E_P_V_ACCESORIOS
  FOREIGN KEY (ID_ARTICULO) --ID_ACCESORIO
  REFERENCES E_ARTICULOS(ID_ARTICULO) --E_ACCESORIOS(ID_ACCESORIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE EPV_ARTICULOS --EPV_ACCESORIOS
  ADD CONSTRAINT PRESTAMO_FK_E_P_V_ARTICULOS --PRESTAMO_FK_E_P_V_ACCESORIOS
  FOREIGN KEY (ID_PRESTAMO)
  REFERENCES E_PRESTAMOS(ID_PRESTAMO)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE EV_HORASSERVICIO
  ADD CONSTRAINT HORASSERVICIO_FK_VIDEOPROYECTOR
  FOREIGN KEY (ID_VIDEOPROYECTOR)
  REFERENCES E_VIDEOPROYECTORES(ID_VIDEOPROYECTOR)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE EV_ESTATUS
  ADD CONSTRAINT ESTATUS_FK_VIDEOPROYECTOR
  FOREIGN KEY (ID_VIDEOPROYECTOR)
  REFERENCES E_VIDEOPROYECTORES(ID_VIDEOPROYECTOR)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

  ALTER TABLE E_PRESTAMOS 
  ADD CONSTRAINT PRESTAMOS_FK_REPORTE_VIDEOPROYECTOR 
  FOREIGN KEY (ID_REPORTE_VIDEOPROYECTOR) 
  REFERENCES E_REP_VIDEOPROYECTORES(ID_REPORTE_VIDEOPROYECTOR) 
  ON DELETE CASCADE 
  ON UPDATE CASCADE;

  ALTER TABLE E_REP_VIDEOPROYECTORES
  ADD CONSTRAINT REPORTES_VID_FK_PROFESOR
  FOREIGN KEY (ID_PROFESOR)
  REFERENCES E_PROFESORES(ID_PROFESOR)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

/* INDEX */

CREATE INDEX REGPREST_TO_DESC ON E_PRESTAMOS(ID_PRESTAMO DESC);

CREATE INDEX REGREPORT_V_TO_DESC ON E_REP_VIDEOPROYECTORES(ID_REPORTE_VIDEOPROYECTOR DESC);

CREATE INDEX LOG_TO_DESC ON E_LOG_MOVIMIENTOS(ID_LOG DESC);

/* nuevos datos */

INSERT INTO E_AULAS(NOMBRE) VALUES
('A01'),('A02'),('A03'),('A04'),('A05'),('A06'),('A07'),('A08'),('A09'),('A10'),
('A11'),('A12'),('A13'),('A14'),('A15'),('A16'),('A17'),('A18'),('A19'),('A20'),
('A21'),('A22'),('A23'),('A24'),('A25'),('A26'),('A27'),('A28'),('A29'),('A30'),
('A31'),('A32'),('A33'),('A34'),('A35'),('A36'),('A37'),
('B01'),('B02'),('B03'),
('C01'),('C02'),('C03'),('C04'),
('D01'),('D02'),('D03'),('D04'),('D05'),('D06'),
('E01'),('E02'),('E03'),('E04'),
('R01'),('R02'),('R03'),('CC1'),('CC2'),('CC3'),
('Lab. de Electrónica'),('Lab. de Mecatrónica'),('Lab. de Química'),
('Lab. de Automotriz'),('Taller de Construcción');

INSERT INTO E_DEPARTAMENTOS(nombre, abbrev, encargado) VALUES
('Metal-Mecánica', 'M. MEC.', 'Ing. Florez Alonso Alejandro'),
('Ciencias Básicas', 'C. B.', 'Cota Ramírez Anabel'),
('Ciencias de la Tierra', 'C. T.', 'Arq. Torres Ruiz Nydia'),
('Electrica y Elctrónica', 'Elec. Elec.','Ing. Muñiz Elizalde José David'),
('Sistemas y Computación', 'SyC', 'Ing. Amezcua Fierros Claudia'),
('Ciencias Económico-Administrativas', 'CEA', 'Lic. Vázquez Olvera Ernesto'),
('Desarrollo Académico', 'Des. Académico', 'Ing. Pacheco Hernández Raquel');