/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyector;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.ToolTipManager;
import proyector.dataBase.crud.AccesorioDB;
import proyector.dataBase.crud.AulaDB;
import proyector.dataBase.crud.DepartamentoDB;
import proyector.dataBase.crud.LeerInicio;
import proyector.dataBase.crud.PrestamoDB;
import proyector.dataBase.crud.ProfesorDB;
import proyector.dataBase.crud.VideoproyectorDB;

/**
 *
 * @author JuanGSot
 */
public class ADevolucion extends javax.swing.JFrame {

    ImageIcon img = new ImageIcon("./src/imagenes/logo-adm.png");
    String date = new SimpleDateFormat("dd-MM-yyyy").format(new Date());
    private static ArrayList<String> accesorios = new ArrayList<String>();
    /**
     * Creates new form ADevolucion
     */
    public ADevolucion() {
        initComponents();
        panelOPC.setVisible(false);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);     //indica la velocidad de movimiento del scroll
        labelFecha.setText(date);                                   //coloca la fecha
        
        //ocultar info desde jcrollpane
        lblHiden.setVisible(false);
        txtProyNSerie.setTransferHandler(null);
        dibujarDevoluciones();
        cargarComboProy();
        combPnl.setVisible(false);
//        jComboBox1.setVisible(false);
        hiddenProf.setVisible(false);
        hiddenProf1.setVisible(false);
        txtProyNSerie.requestFocusInWindow();
        Timer timer = new Timer(500, (ActionEvent e) -> {
            reloj();                                                //coloca la hora
        });
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.setInitialDelay(0);
        timer.start();
    }

    /**
     * Se encarga de colocar la hora con un formato especifico
     */
    public void reloj() {
        labelHora.setText(new SimpleDateFormat("hh:mm:ss a").format(new Date()));
    }

    public void dibujarDevoluciones(){
        try {
            PrestamoDB pres = new PrestamoDB();
            String[][] datos = pres.getPrestamos(true,false);
            System.out.println("Prestamos existentes: " + pres.getPrestamosCount(true));
            for(String[] dato: datos){
                miPanel(dato);
            }    
            
            //acomodar componentes
            System.out.println("Dibujar cada prestamo");
            int comp = pnlContenedor.getComponentCount();
            float filas = (comp / 4) + (comp % 4 == 0 ? 0 : 1);
            int altura = (int) (279 * filas); //la altura de cada jPane mas el espacio extra por la cantidad de elementos
            pnlContenedor.setPreferredSize(new Dimension(890, altura));
        } catch (SQLException ex) {
            Logger.getLogger(ADevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cargarComboProy() {
        try {
            VideoproyectorDB proyect = new VideoproyectorDB();
            HashMap<String, String> map = proyect.devolucionCombo();             //obtiene los datos -en DB ya se comprobo que esta disponible
            Map<String, String> map1 = new TreeMap<>(map);                      //ordena el HashMap
            jComboBox1.removeAllItems();
            if(map1.isEmpty()){
                jComboBox1.setEnabled(false);
            }else{
                for (String s : map1.keySet()) {
                    // agrega los datos al comboBox
                    jComboBox1.addItem(s);
                    System.out.println("S:" + s);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(AlPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dialogUsuario = new javax.swing.JDialog();
        dlgBk = new javax.swing.JPanel();
        pnlColor = new javax.swing.JPanel();
        pnlColor1 = new javax.swing.JPanel();
        pnlFormulario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuarioVal = new javax.swing.JTextField();
        pnlBtnGuardar = new javax.swing.JPanel();
        icoGuardar1 = new javax.swing.JLabel();
        lblTxtGuardar1 = new javax.swing.JLabel();
        pnlBtnCerrar = new javax.swing.JPanel();
        icoCerrar1 = new javax.swing.JLabel();
        lblTxtCerrar1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblHiden = new javax.swing.JLabel();
        pryArt = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblNProy = new javax.swing.JLabel();
        btnReportarAcc = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        hiddenProf = new javax.swing.JLabel();
        dlgReporte = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtProf = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        lblListItems = new javax.swing.JLabel();
        btnReportar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        hiddenProf1 = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        pnlCabecera = new javax.swing.JPanel();
        lblIco1 = new javax.swing.JLabel();
        lblIco2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        btnMenu = new javax.swing.JToggleButton();
        btnRegresar = new javax.swing.JButton();
        panelOPC = new javax.swing.JPanel();
        ico3 = new javax.swing.JLabel();
        ico4 = new javax.swing.JLabel();
        ico5 = new javax.swing.JLabel();
        ico6 = new javax.swing.JLabel();
        ico7 = new javax.swing.JLabel();
        ico8 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPnDevolver = new javax.swing.JPanel();
        lblIco3 = new javax.swing.JLabel();
        lblTextoDev = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlContenedor = new javax.swing.JPanel();
        chkBLista = new javax.swing.JCheckBox();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        noSeriePnl = new javax.swing.JPanel();
        barraSeparadora = new javax.swing.JPanel();
        txtProyNSerie = new javax.swing.JTextField();
        combPnl = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();

        dialogUsuario.setMinimumSize(new java.awt.Dimension(589, 321));
        dialogUsuario.setModal(true);
        dialogUsuario.setUndecorated(true);
        dialogUsuario.setResizable(false);

        dlgBk.setBackground(new java.awt.Color(255, 103, 96));
        dlgBk.setMinimumSize(new java.awt.Dimension(589, 321));

        pnlColor.setBackground(new java.awt.Color(158, 163, 13));
        pnlColor.setPreferredSize(new java.awt.Dimension(25, 321));

        javax.swing.GroupLayout pnlColorLayout = new javax.swing.GroupLayout(pnlColor);
        pnlColor.setLayout(pnlColorLayout);
        pnlColorLayout.setHorizontalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlColorLayout.setVerticalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlColor1.setBackground(new java.awt.Color(206, 210, 72));
        pnlColor1.setPreferredSize(new java.awt.Dimension(15, 0));

        javax.swing.GroupLayout pnlColor1Layout = new javax.swing.GroupLayout(pnlColor1);
        pnlColor1.setLayout(pnlColor1Layout);
        pnlColor1Layout.setHorizontalGroup(
            pnlColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pnlColor1Layout.setVerticalGroup(
            pnlColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlFormulario.setOpaque(false);
        pnlFormulario.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Validar Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlFormulario.add(jLabel4, gridBagConstraints);

        txtUsuarioVal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtUsuarioVal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioVal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtUsuarioVal.setMinimumSize(new java.awt.Dimension(250, 35));
        txtUsuarioVal.setPreferredSize(new java.awt.Dimension(250, 35));
        txtUsuarioVal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioValKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 20, 20, 20);
        pnlFormulario.add(txtUsuarioVal, gridBagConstraints);

        pnlBtnGuardar.setBackground(new java.awt.Color(239, 239, 239));
        pnlBtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnGuardarMouseExited(evt);
            }
        });
        pnlBtnGuardar.setLayout(new java.awt.GridBagLayout());

        icoGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_22px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 14, 4, 0);
        pnlBtnGuardar.add(icoGuardar1, gridBagConstraints);

        lblTxtGuardar1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblTxtGuardar1.setForeground(new java.awt.Color(0, 191, 255));
        lblTxtGuardar1.setText("Guardar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnlBtnGuardar.add(lblTxtGuardar1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlFormulario.add(pnlBtnGuardar, gridBagConstraints);

        pnlBtnCerrar.setBackground(new java.awt.Color(239, 239, 239));
        pnlBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnCerrarMouseExited(evt);
            }
        });
        pnlBtnCerrar.setLayout(new java.awt.GridBagLayout());

        icoCerrar1.setForeground(new java.awt.Color(231, 76, 60));
        icoCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 14, 4, 0);
        pnlBtnCerrar.add(icoCerrar1, gridBagConstraints);

        lblTxtCerrar1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblTxtCerrar1.setForeground(new java.awt.Color(231, 76, 60));
        lblTxtCerrar1.setText("Cerrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 14);
        pnlBtnCerrar.add(lblTxtCerrar1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlFormulario.add(pnlBtnCerrar, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/More Info_22px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Puede presionar enter o el boton Guardar para validar");

        lblHiden.setText("jLabel7");

        javax.swing.GroupLayout dlgBkLayout = new javax.swing.GroupLayout(dlgBk);
        dlgBk.setLayout(dlgBkLayout);
        dlgBkLayout.setHorizontalGroup(
            dlgBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBkLayout.createSequentialGroup()
                .addComponent(pnlColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dlgBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgBkLayout.createSequentialGroup()
                        .addGroup(dlgBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgBkLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(dlgBkLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgBkLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHiden)
                        .addGap(43, 43, 43))))
        );
        dlgBkLayout.setVerticalGroup(
            dlgBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlColor1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
            .addGroup(dlgBkLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblHiden)
                .addGap(1, 1, 1)
                .addGroup(dlgBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout dialogUsuarioLayout = new javax.swing.GroupLayout(dialogUsuario.getContentPane());
        dialogUsuario.getContentPane().setLayout(dialogUsuarioLayout);
        dialogUsuarioLayout.setHorizontalGroup(
            dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dlgBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogUsuarioLayout.setVerticalGroup(
            dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dlgBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogUsuario.getAccessibleContext().setAccessibleParent(this);

        pryArt.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pryArt.setTitle("[Articulos]");
        pryArt.setMinimumSize(new java.awt.Dimension(320, 295));
        pryArt.setModal(true);
        pryArt.setUndecorated(true);
        pryArt.setPreferredSize(new java.awt.Dimension(320, 295));
        pryArt.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(195, 83, 93));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 213, 217), 4));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 295));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 295));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html>Articulos solicitados con el siguiente<br>Video Proyector:</html>");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, -1, -1));

        lblNProy.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblNProy.setForeground(new java.awt.Color(255, 255, 255));
        lblNProy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNProy.setText("lblNombreProyector");
        jPanel1.add(lblNProy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 320, -1));

        btnReportarAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportar-22px.png"))); // NOI18N
        btnReportarAcc.setText("Reportar!");
        btnReportarAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarAccActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportarAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 170, 90));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html><center>Para reportar más de un elemento mantenga<br>presionado la tecla CTRL y con clic izquierdo<br>seleccione los demas elementos</center></html>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 300, 50));

        hiddenProf.setText("SoyProfe");
        jPanel1.add(hiddenProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        javax.swing.GroupLayout pryArtLayout = new javax.swing.GroupLayout(pryArt.getContentPane());
        pryArt.getContentPane().setLayout(pryArtLayout);
        pryArtLayout.setHorizontalGroup(
            pryArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(pryArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pryArtLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pryArtLayout.setVerticalGroup(
            pryArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
            .addGroup(pryArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pryArtLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dlgReporte.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReporte.setTitle("[Reporte de Artículos]");
        dlgReporte.setMinimumSize(new java.awt.Dimension(750, 420));
        dlgReporte.setModal(true);
        dlgReporte.setPreferredSize(new java.awt.Dimension(750, 420));

        jPanel2.setBackground(new java.awt.Color(255, 138, 101));
        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reporte de Pérdida/Fallos sobre Artículo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 13, 720, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descripcion corta sobre el problema:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descripción de la falla o como fue perdido el artículo:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Profesor:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtTitulo.setPreferredSize(new java.awt.Dimension(280, 30));
        jPanel2.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 390, 30));

        txtProf.setEditable(false);
        txtProf.setBackground(new java.awt.Color(255, 255, 255));
        txtProf.setEnabled(false);
        txtProf.setPreferredSize(new java.awt.Dimension(280, 30));
        jPanel2.add(txtProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 390, -1));

        txtDesc.setColumns(20);
        txtDesc.setLineWrap(true);
        txtDesc.setRows(5);
        txtDesc.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtDesc);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 390, 110));

        jPanel3.setBackground(new java.awt.Color(255, 183, 77));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.gray), "Artículo(s)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        lblListItems.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblListItems.setForeground(new java.awt.Color(255, 255, 255));
        lblListItems.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblListItems.setText("jLabel14");
        lblListItems.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblListItems.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        lblListItems.setMinimumSize(new java.awt.Dimension(238, 218));
        lblListItems.setPreferredSize(new java.awt.Dimension(238, 218));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 250, 270));

        btnReportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportar-22px.png"))); // NOI18N
        btnReportar.setText("Reportar");
        btnReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 345, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCancelar.setText("Limpiar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 345, -1, -1));

        hiddenProf1.setText("SoyProfe");
        jPanel2.add(hiddenProf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        javax.swing.GroupLayout dlgReporteLayout = new javax.swing.GroupLayout(dlgReporte.getContentPane());
        dlgReporte.getContentPane().setLayout(dlgReporteLayout);
        dlgReporteLayout.setHorizontalGroup(
            dlgReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgReporteLayout.setVerticalGroup(
            dlgReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Devolución]");
        setIconImage(img.getImage());
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setMinimumSize(new java.awt.Dimension(1024, 600));
        pnlBackground.setPreferredSize(new java.awt.Dimension(1024, 600));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecera.setBackground(new java.awt.Color(1, 200, 1));
        pnlCabecera.setMinimumSize(new java.awt.Dimension(1024, 83));
        pnlCabecera.setPreferredSize(new java.awt.Dimension(1024, 83));

        lblIco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tecnm2.png"))); // NOI18N

        lblIco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sep.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hora");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha");

        labelHora.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 255, 255));
        labelHora.setText("00:00:00 PM");

        labelFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("00-00-0000");

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIco1)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(labelHora)
                .addGap(107, 107, 107)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(labelFecha)
                .addGap(36, 36, 36)
                .addComponent(lblIco2)
                .addContainerGap())
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIco1)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIco2))
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(labelHora))
                    .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(labelFecha))))
        );

        pnlBackground.add(pnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Checklist_24px.png"))); // NOI18N
        btnMenu.setMaximumSize(new java.awt.Dimension(40, 37));
        btnMenu.setMinimumSize(new java.awt.Dimension(40, 37));
        btnMenu.setPreferredSize(new java.awt.Dimension(40, 37));
        btnMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnMenuItemStateChanged(evt);
            }
        });
        pnlBackground.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back To_35px.png"))); // NOI18N
        btnRegresar.setMaximumSize(new java.awt.Dimension(40, 37));
        btnRegresar.setMinimumSize(new java.awt.Dimension(40, 37));
        btnRegresar.setPreferredSize(new java.awt.Dimension(40, 37));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlBackground.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        panelOPC.setBackground(new java.awt.Color(250, 250, 250));
        panelOPC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 173, 179), 1, true));
        panelOPC.setLayout(new java.awt.GridBagLayout());

        ico3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo_32px.png"))); // NOI18N
        ico3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        panelOPC.add(ico3, gridBagConstraints);

        ico4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registr_32px.png"))); // NOI18N
        ico4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico4, gridBagConstraints);

        ico5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prof_42px.png"))); // NOI18N
        ico5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        panelOPC.add(ico5, gridBagConstraints);

        ico6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/depart_42px.png"))); // NOI18N
        ico6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico6, gridBagConstraints);

        ico7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aul_42px.png"))); // NOI18N
        ico7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico7MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 4, 0);
        panelOPC.add(ico7, gridBagConstraints);

        ico8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Video Projector_42px.png"))); // NOI18N
        ico8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico8MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 0);
        panelOPC.add(ico8, gridBagConstraints);

        pnlBackground.add(panelOPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 50, 350));

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        lblTitulo.setText("Devolución");
        pnlBackground.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("No. de Serie del VideoProyector:");
        pnlBackground.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        btnPnDevolver.setBackground(new java.awt.Color(239, 239, 239));
        btnPnDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPnDevolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPnDevolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPnDevolverMouseExited(evt);
            }
        });
        btnPnDevolver.setLayout(new java.awt.GridBagLayout());

        lblIco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_22px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 12, 0);
        btnPnDevolver.add(lblIco3, gridBagConstraints);

        lblTextoDev.setBackground(new java.awt.Color(0, 191, 255));
        lblTextoDev.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTextoDev.setForeground(new java.awt.Color(0, 191, 255));
        lblTextoDev.setText("Registrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        btnPnDevolver.add(lblTextoDev, gridBagConstraints);

        pnlBackground.add(btnPnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 254, 130, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(890, 290));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(890, 290));

        pnlContenedor.setBackground(new java.awt.Color(121, 129, 208));
        pnlContenedor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 9));
        jScrollPane1.setViewportView(pnlContenedor);

        pnlBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 308, -1, -1));

        chkBLista.setText("elegir de una lista");
        chkBLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBListaActionPerformed(evt);
            }
        });
        pnlBackground.add(chkBLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        noSeriePnl.setBackground(new java.awt.Color(255, 255, 255));

        barraSeparadora.setBackground(new java.awt.Color(125, 119, 105));
        barraSeparadora.setMinimumSize(new java.awt.Dimension(330, 3));
        barraSeparadora.setPreferredSize(new java.awt.Dimension(330, 3));

        javax.swing.GroupLayout barraSeparadoraLayout = new javax.swing.GroupLayout(barraSeparadora);
        barraSeparadora.setLayout(barraSeparadoraLayout);
        barraSeparadoraLayout.setHorizontalGroup(
            barraSeparadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        barraSeparadoraLayout.setVerticalGroup(
            barraSeparadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        txtProyNSerie.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtProyNSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProyNSerie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtProyNSerie.setMinimumSize(new java.awt.Dimension(250, 30));
        txtProyNSerie.setPreferredSize(new java.awt.Dimension(250, 30));
        txtProyNSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProyNSerieKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout noSeriePnlLayout = new javax.swing.GroupLayout(noSeriePnl);
        noSeriePnl.setLayout(noSeriePnlLayout);
        noSeriePnlLayout.setHorizontalGroup(
            noSeriePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(noSeriePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(noSeriePnlLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(noSeriePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtProyNSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(barraSeparadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        noSeriePnlLayout.setVerticalGroup(
            noSeriePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(noSeriePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(noSeriePnlLayout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(txtProyNSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(barraSeparadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        combPnl.setBackground(new java.awt.Color(255, 255, 255));

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(330, 35));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout combPnlLayout = new javax.swing.GroupLayout(combPnl);
        combPnl.setLayout(combPnlLayout);
        combPnlLayout.setHorizontalGroup(
            combPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(combPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(combPnlLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        combPnlLayout.setVerticalGroup(
            combPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(combPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(combPnlLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLayeredPane1.setLayer(noSeriePnl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(combPnl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(noSeriePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(combPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(noSeriePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addComponent(combPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        pnlBackground.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ico3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico3MouseClicked
        AlPrestamo pres = new AlPrestamo();
        pres.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico3MouseClicked

    private void ico4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico4MouseClicked
        ARegistro reg = new ARegistro();
        reg.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico4MouseClicked

    private void ico5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico5MouseClicked
        try {
            Profesor profe = new Profesor();
            profe.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AlPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ico5MouseClicked

    private void ico6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico6MouseClicked
        try {
            Departamento depart = new Departamento();
            depart.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AlPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ico6MouseClicked

    private void ico7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico7MouseClicked
        try {
            Aula aula = new Aula();
            aula.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ADevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ico7MouseClicked

    private void ico8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico8MouseClicked
        try {
            Videoproyector vid = new Videoproyector();
            vid.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ADevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ico8MouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnMenuItemStateChanged
        if (btnMenu.isSelected()) {
            panelOPC.setVisible(true);
        } else {
            panelOPC.setVisible(false);
        }
    }//GEN-LAST:event_btnMenuItemStateChanged

    private void btnPnDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPnDevolverMouseClicked
        btnPnDevolver.setBackground(new Color(239,239,239));
        String datos = txtProyNSerie.getText().trim();
        if (!datos.isEmpty()){
            //comprobar que exisa un prestamo
            try{
                PrestamoDB dev = new PrestamoDB();
                if (dev.getExistePrestamoProy(datos)){
                    dialogUsuario.setLocationRelativeTo(pnlBackground);
                    dialogUsuario.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "El videoproyector indicado\nno tiene registro de que haya sido prestado");
                    txtProyNSerie.setText("");
                }
            }catch(Exception ex){
                System.out.println("Error al cargar si existen prestamos: " + ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Cuadro de texto vacio!!!");
        }
    }//GEN-LAST:event_btnPnDevolverMouseClicked

    private void btnPnDevolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPnDevolverMouseEntered
        btnPnDevolver.setBackground(new Color(0,191,255));
    }//GEN-LAST:event_btnPnDevolverMouseEntered

    private void btnPnDevolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPnDevolverMouseExited
        btnPnDevolver.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_btnPnDevolverMouseExited

    private void pnlBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnCerrarMouseClicked
        pnlBtnCerrar.setBackground(new Color(239,239,239));
        
        dialogUsuario.setVisible(false);
        dialogUsuario.dispose();
        txtUsuarioVal.setText("");
    }//GEN-LAST:event_pnlBtnCerrarMouseClicked

    private void pnlBtnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnCerrarMouseEntered
        pnlBtnCerrar.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_pnlBtnCerrarMouseEntered

    private void pnlBtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnCerrarMouseExited
        pnlBtnCerrar.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_pnlBtnCerrarMouseExited

    private void pnlBtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnGuardarMouseClicked
        accionarLiberacion();
    }//GEN-LAST:event_pnlBtnGuardarMouseClicked
    public void accionarLiberacion(){
        String proyector = txtProyNSerie.getText().trim();
        String credencial = txtUsuarioVal.getText().trim();
        try {    
            //revisar que exista el videoproyector txtProyNSerie
            VideoproyectorDB profe = new VideoproyectorDB();
            if(profe.getExisteProyector(proyector)){
                //revisar que no este en blanco el dato de txtUsuarioVal
                if(!credencial.isEmpty()){
                    LeerInicio leer = new LeerInicio();
                    if (leer.getExisteUsuario(credencial)){
                        //comprobar que exisa un prestamo
                        PrestamoDB dev = new PrestamoDB();
                        if (dev.getExistePrestamoProy(proyector)){
                            // generar actualizacion
                            // liberar distintos articulos
                            dev.updPrestamo(proyector, credencial);    
                            System.out.println("El prestamo se libero!: \n-Proyector:" + proyector + "\n-Credencial: " + credencial);
                            pnlContenedor.removeAll();
                            pnlContenedor.repaint();
                            dibujarDevoluciones();
                            ImageIcon iconJPane = new ImageIcon("./src/imagenes/Ok.png");
                            JOptionPane.showMessageDialog(null, "El videoproyector ahora se registra como disponible", "Información", JOptionPane.INFORMATION_MESSAGE, iconJPane);
                            txtProyNSerie.requestFocusInWindow();
                            cargarComboProy();
                        }else{
                            JOptionPane.showMessageDialog(null, "El videoproyector indicado \nno se ha prestado", "Información", JOptionPane.INFORMATION_MESSAGE);
                        }
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Este usuario no se encuentra registrado\ny no es capaz de usar esta caracteristica", "Información", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "El videoproyector indicado no se ha prestado");
            }
            txtProyNSerie.setText("");
            txtUsuarioVal.setText("");
            dialogUsuario.setVisible(false);
            
            chkBLista.setSelected(false);
            noSeriePnl.setVisible(true);
            combPnl.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ADevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtProyNSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProyNSerieKeyTyped
        if (txtProyNSerie.getText().length() >= 20) {
            evt.consume();
        }
        
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            String datos = txtProyNSerie.getText().trim();
            if (!datos.isEmpty()){
                //comprobar que exisa un prestamo
                try{
                    PrestamoDB dev = new PrestamoDB();
                    if (dev.getExistePrestamoProy(datos)){
                        dialogUsuario.setLocationRelativeTo(pnlBackground);
                        dialogUsuario.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "El videoproyector indicado\nno tiene registro de que haya sido prestado");
                        txtProyNSerie.setText("");
                    }
                }catch(Exception ex){
                    System.out.println("Error al cargar si existen prestamos: " + ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Cuadro de texto vacio!!!");
            }
        }
    }//GEN-LAST:event_txtProyNSerieKeyTyped

    private void pnlBtnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnGuardarMouseEntered
        pnlBtnGuardar.setBackground(new Color(0,191,255));
    }//GEN-LAST:event_pnlBtnGuardarMouseEntered

    private void pnlBtnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnGuardarMouseExited
        pnlBtnGuardar.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_pnlBtnGuardarMouseExited

    private void txtUsuarioValKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioValKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            accionarLiberacion();
        }
    }//GEN-LAST:event_txtUsuarioValKeyTyped

    private void chkBListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBListaActionPerformed
        if(chkBLista.isSelected()){
            noSeriePnl.setVisible(false);
            combPnl.setVisible(true);
             try {
                VideoproyectorDB proy = new VideoproyectorDB();
                HashMap<String, String> map = proy.devolucionCombo();
                if(!map.isEmpty()){
                    jComboBox1.setSelectedIndex(0);
                    String proyNoSerie = map.get(jComboBox1.getSelectedItem().toString());
                    System.out.println("No_Serie videoproyector seleccionado: " + proyNoSerie);
                    txtProyNSerie.setText(proyNoSerie);
                }
            } catch (SQLException ex) {
                System.out.println("Error al recuperar informacion videoproyector ComboBox: " + ex);
            } catch (Exception e) {
                System.out.println("!!!!!!Error al recuperar informacion videoproyector ComboBox: " + e);
            }
        }else{
            noSeriePnl.setVisible(true);
            combPnl.setVisible(false);
        }
    }//GEN-LAST:event_chkBListaActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
         if(chkBLista.isSelected()){
            try {
                VideoproyectorDB proyector = new VideoproyectorDB();                         //instancia de proyector
                HashMap<String, String> map = proyector.devolucionCombo();                       //genera un hash con el noSerie y nombre del proyector
                if(!map.isEmpty()){
                    String proyNoSerie = map.get(jComboBox1.getSelectedItem().toString());     //del elemento seleccionado recupera el noSerie
                    System.out.println(".::NoSerie de Proyector seleccionado\n.::stateChanged: " + proyNoSerie);
                    txtProyNSerie.setText(proyNoSerie);
                }
            } catch (SQLException ex) {
                System.out.println("Error combVid al efecti statedSchanged: " + ex);
            }catch(Exception e){
                System.out.println("!!!!!!Error combVis al efectisimo statedChange: " + e);
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
         if (chkBLista.isSelected()) {
            try {
                VideoproyectorDB proy = new VideoproyectorDB();                         //instancia de proyector
                HashMap<String, String> map = proy.devolucionCombo();                       //genera un hash con el noSerie y nombre del proyector
                if(!map.isEmpty()){
                    String proyNoSerie = map.get(jComboBox1.getSelectedItem().toString());     //del elemento seleccionado recupera el noSerie
                    System.out.println(".::No_Serie proyector comboVid: " + proyNoSerie);
                    txtProyNSerie.setText(proyNoSerie);
                }
            } catch (SQLException ex) {
                System.out.println("Error al recuperar informacion videoproyector ComboBox: " + ex);
            }
        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
         if (chkBLista.isSelected()) {
            try {
                VideoproyectorDB proyector = new VideoproyectorDB();                         //instancia de proyector
                HashMap<String, String> map = proyector.devolucionCombo();                       //genera un hash con el noSerie y nombre del proyector
                if(!map.isEmpty()){
                    String proyNoSerie = map.get(jComboBox1.getSelectedItem().toString());     //del elemento seleccionado recupera el noSerie
                    System.out.println(".::NoSerie de Proyector seleccionado\n.::focusLost: " + proyNoSerie);
                    txtProyNSerie.setText(proyNoSerie);
                }
            } catch (SQLException ex) {
                System.out.println("Error combVid al perder focus: " + ex);
            }
        }
    }//GEN-LAST:event_jComboBox1FocusLost

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        pryArt.setVisible(false);
        pryArt.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnReportarAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarAccActionPerformed
        accesorios.clear();
        List<String> list = new ArrayList<String>();
        list = jList1.getSelectedValuesList();
        String[] arr = list.stream().toArray(String[]::new);
        System.out.println("Arr: " + Arrays.toString(arr));
        if(arr.length > 0){
            String bulletList = "<html><ul>";
            for(String i: arr){ bulletList += "<li>"+i+"</li><br>"; accesorios.add(i); }
            bulletList += "</ul></html>";
            lblListItems.setText(bulletList);

            hiddenProf1.setText(hiddenProf.getText());
            try{
            String[] profe = new ProfesorDB().getProfesor(hiddenProf.getText());
            txtProf.setText(profe[2] + " " + profe[3] + " " +profe[4]);
            }catch(SQLException ex){ System.out.println("Error al recuperar nombre del profesor en reporte: " + ex); }

            dlgReporte.setLocationRelativeTo(this);
            dlgReporte.setVisible(true);
            pryArt.setVisible(false);
            pryArt.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Al menos debe seleccionar un articulo para generar el reporte");
        }
    }//GEN-LAST:event_btnReportarAccActionPerformed

    private void btnReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarActionPerformed
        String profe = hiddenProf1.getText();
        String titulo = txtTitulo.getText().trim();
        String detalles = txtDesc.getText().trim();
        int i = 0;
        if(!titulo.isEmpty() && !detalles.isEmpty()){
            String[] acc = new String[accesorios.size()];
            Iterator<String> iterar = accesorios.iterator();
            while(iterar.hasNext()){ acc[i] = iterar.next(); i++; }
            
            Calendar c = Calendar.getInstance();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm");
            String fecha = dateFormat.format(c.getTime());
            System.out.println("Profe: " + profe + "\nDescCorta: " + titulo + "\nDetalles: " + detalles + "\nArticulos: " + Arrays.toString(acc)+ "\nFecha: " + fecha);
            
            JOptionPane.showMessageDialog(this, "Reporte Realizado!\nSe descartaran del inventario los artículos que ha indicado","Información", JOptionPane.INFORMATION_MESSAGE);
            
            dlgReporte.setVisible(false);
            dlgReporte.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Recuerde completar todos los campos");
        }
    }//GEN-LAST:event_btnReportarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtTitulo.setText("");
        txtDesc.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void miPanel(String[] datos) throws SQLException{
        JPanel pnlVidDetalles = new JPanel();
        GridBagConstraints c = new GridBagConstraints();
        
        pnlVidDetalles.setOpaque(false);
        pnlVidDetalles.setForeground(new Color(255, 255, 255));
        pnlVidDetalles.setPreferredSize(new Dimension(200, 270));
        pnlVidDetalles.setLayout(new GridBagLayout());
        pnlVidDetalles.setBorder(new RoundedBorder(25));
        
        JLabel vid = new JLabel("Videoproyector");
        vid.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); 
        vid.setForeground(new java.awt.Color(255, 255, 255));
        c.insets = new Insets(0, 30, 15, 0);
        pnlVidDetalles.add(vid, c);
        
        JLabel vidNom = new JLabel();
        vidNom.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); 
        vidNom.setForeground(new java.awt.Color(255, 255, 255));
        c = new GridBagConstraints();
        c.anchor = GridBagConstraints.LINE_START;
        c.insets = new Insets(0, 10, 15, 0);
        pnlVidDetalles.add(vidNom, c);
        
        JPanel pnlSeparador = new JPanel();
        pnlSeparador.setBackground(new Color(241, 245, 248));
        pnlSeparador.setMinimumSize(new Dimension(240, 2));
        pnlSeparador.setPreferredSize(new Dimension(240, 2));
        
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 2;
        pnlVidDetalles.add(pnlSeparador, c);
        
        JPanel pnlBody = new JPanel();
        pnlBody.setOpaque(false);
        pnlBody.setLayout(new GridBagLayout());

        JLabel lblProfe = new JLabel("Profesor:");
        lblProfe.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        lblProfe.setForeground(new Color(255, 255, 255));
        c = new GridBagConstraints();
        c.anchor = GridBagConstraints.WEST;
        c.insets = new Insets(12, 0, 0, 0);
        pnlBody.add(lblProfe, c);
        
        
        JLabel lblDtsProfe = new JLabel();
        lblDtsProfe.setFont(new java.awt.Font("Verdana", 0, 9));
        lblDtsProfe.setForeground(new Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 1;
        c.insets = new Insets(2, 0, 2, 2);
        pnlBody.add(lblDtsProfe, c);
        
        JLabel lblFecha = new JLabel("Solicitado a las:");
        lblFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); 
        lblFecha.setForeground(new Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 2;
        c.anchor = GridBagConstraints.WEST;
        c.insets = new java.awt.Insets(7, 0, 0, 0);
        pnlBody.add(lblFecha, c);
        
        JLabel lblDtsFecha = new JLabel();
        lblDtsFecha.setFont(new java.awt.Font("Verdana", 0, 9));
        lblDtsFecha.setForeground(new java.awt.Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 3;
        c.insets = new Insets(7, 0, 7, 0);
        pnlBody.add(lblDtsFecha, c);
        
        JLabel lblAula = new JLabel("Aula:");
        lblAula.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        lblAula.setForeground(new Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 4;
        c.anchor = GridBagConstraints.WEST;
        c.insets = new Insets(7, 0, 0, 0);
        pnlBody.add(lblAula, c);
        
        JLabel lblDtsAula = new JLabel();
        lblDtsAula.setFont(new java.awt.Font("Verdana", 0, 9));
        lblDtsAula.setForeground(new Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 5;
        c.insets = new Insets(2, 0, 2, 0);
        pnlBody.add(lblDtsAula, c);
        
        JLabel lblDepto = new JLabel("Departamento de:");
        lblDepto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblDepto.setForeground(new java.awt.Color(255, 255, 255));
        lblDepto.setText("Departamento de:");
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 6;
        c.anchor = java.awt.GridBagConstraints.WEST;
        c.insets = new java.awt.Insets(7, 0, 0, 0);
        pnlBody.add(lblDepto, c);

        JLabel lblDtsDepto = new JLabel();
        lblDtsDepto.setFont(new java.awt.Font("Verdana", 0, 9)); // NOI18N
        lblDtsDepto.setForeground(new java.awt.Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 7;
        c.insets = new java.awt.Insets(8, 0, 5, 0);
        pnlBody.add(lblDtsDepto, c);
        
        JButton btnArt = new JButton("-Articulos-");
        btnArt.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 8;
        c.insets = new Insets(4, 0, 0, 0);
        pnlBody.add(btnArt, c);
        
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 2;
        c.gridwidth = 2;
        
        //datos
        String[] profe = new ProfesorDB().getProfesor(datos[4]);
        String [] accesoriosAr = new AccesorioDB().getAccDeProf(datos[4]);
        String pryNom = new VideoproyectorDB().getProyector(new VideoproyectorDB().getProyectorNoSerie(datos[3]))[1];
        
        vidNom.setText(pryNom);
        lblDtsProfe.setText("<html>" + profe[2] + "<br>" + profe[3] + " " +profe[4] + "</html>");
        lblDtsFecha.setText(datos[6].substring(0,16));
        lblDtsAula.setText(new AulaDB().getAula(Integer.parseInt(datos[5])) );
        lblDtsDepto.setText(new DepartamentoDB().getDepartamento(Integer.parseInt(profe[1]))[0]);
        
        if(accesoriosAr.length > 0){
            String acc = Arrays.toString(accesoriosAr).replace("[", "").replace("]", "").replaceAll(",", "<br>");
            setToolTipRecursively(pnlVidDetalles, "<html><b>Articulos solicitados con <i>" + pryNom +"</i>:</b><br>" + acc + "</html>");
            btnArt.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) { 
                    lblNProy.setText(pryNom);
                    DefaultListModel<String> listModel = new DefaultListModel<>();
                    for(String miAcc : accesoriosAr){
                        listModel.addElement(miAcc);
                    }
                    jList1.setModel(listModel);
                    // mostrar dialog
                    hiddenProf.setText(datos[4]);
                    pryArt.setLocationRelativeTo(pnlBackground);
                    pryArt.setVisible(true);
                }
            });
        }else{
            btnArt.setEnabled(false);
        }
        
        pnlVidDetalles.add(pnlBody, c);
        pnlVidDetalles.revalidate();
        pnlVidDetalles.repaint();
        pnlContenedor.add(pnlVidDetalles); //añade todo el jpanel al panel principal este jPanel5 se encuentra dentro del jScrolPane
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }
    
    public static void setToolTipRecursively(javax.swing.JComponent c, String text) {

    c.setToolTipText(text);
    ToolTipManager.sharedInstance().setInitialDelay(0);
    for (java.awt.Component cc : c.getComponents())
        if (cc instanceof javax.swing.JComponent)
            setToolTipRecursively((javax.swing.JComponent) cc, text);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADevolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSeparadora;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JToggleButton btnMenu;
    private javax.swing.JPanel btnPnDevolver;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReportar;
    private javax.swing.JButton btnReportarAcc;
    private javax.swing.JCheckBox chkBLista;
    private javax.swing.JPanel combPnl;
    private javax.swing.JDialog dialogUsuario;
    private javax.swing.JPanel dlgBk;
    private javax.swing.JDialog dlgReporte;
    private javax.swing.JLabel hiddenProf;
    private javax.swing.JLabel hiddenProf1;
    private javax.swing.JLabel ico3;
    private javax.swing.JLabel ico4;
    private javax.swing.JLabel ico5;
    private javax.swing.JLabel ico6;
    private javax.swing.JLabel ico7;
    private javax.swing.JLabel ico8;
    private javax.swing.JLabel icoCerrar1;
    private javax.swing.JLabel icoGuardar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel lblHiden;
    private javax.swing.JLabel lblIco1;
    private javax.swing.JLabel lblIco2;
    private javax.swing.JLabel lblIco3;
    private javax.swing.JLabel lblListItems;
    private javax.swing.JLabel lblNProy;
    private javax.swing.JLabel lblTextoDev;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTxtCerrar1;
    private javax.swing.JLabel lblTxtGuardar1;
    private javax.swing.JPanel noSeriePnl;
    private javax.swing.JPanel panelOPC;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBtnCerrar;
    private javax.swing.JPanel pnlBtnGuardar;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlColor;
    private javax.swing.JPanel pnlColor1;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JDialog pryArt;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtProf;
    private javax.swing.JTextField txtProyNSerie;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUsuarioVal;
    // End of variables declaration//GEN-END:variables
}
