package proyector;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.ToolTipManager;
import proyector.dataBase.crud.AccesorioDB;
import proyector.dataBase.crud.AulaDB;
import proyector.dataBase.crud.DepartamentoDB;
import proyector.dataBase.crud.LogDB;
import proyector.dataBase.crud.UsuarioReadDB;
import proyector.dataBase.crud.PrestamoDB;
import proyector.dataBase.crud.ProfesorDB;
import proyector.dataBase.crud.VideoproyectorDB;
import proyector.reportes.GenerarReportes;

/**
 *
 * @author JuanGSot
 */
public class ADevolucion extends javax.swing.JFrame {

    ImageIcon img = new ImageIcon("./src/imagenes/logo-adm.png");
    private static ArrayList<String> accesorios = new ArrayList<String>();
    /**
     * Creates new form ADevolucion
     */
    public ADevolucion() {
        initComponents();
        labelFecha.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
        Timer timer = new Timer(500, (ActionEvent e) -> {
            reloj();
        });
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.setInitialDelay(0);
        timer.start();
        
        panelOPC.setVisible(false);
        scrollContainer.getVerticalScrollBar().setUnitIncrement(16);
        
        pnlCbNSerie.setVisible(false);
        dibujarDevoluciones();
        cargarComboProy();
        txtNSerie.requestFocusInWindow();
        
        lblHiddenProfReportArt.setVisible(false);
        lblHiddenProfReporte.setVisible(false);
    }

    /**
     * Se encarga de colocar la hora con un formato especifico
     */
    public void reloj() {
        labelHora.setText(new SimpleDateFormat("hh:mm:ss a").format(new Date()));
    }

    public void dibujarDevoluciones(){
        try {
            PrestamoDB pres = new PrestamoDB();
            String[][] datos = pres.getPrestamos(true,false);
            
            for(String[] dato: datos){
                miPanel(dato);
            }    
            
            //acomodar componentes
            System.out.println("Prestamos existentes: " + datos.length);
            System.out.println("Dibujar cada prestamo");
            int comp = pnlContenedor.getComponentCount();
            float filas = (comp / 4) + (comp % 4 == 0 ? 0 : 1);
            int altura = (int) (279 * filas); //la altura de cada jPane mas el espacio extra por la cantidad de elementos
            pnlContenedor.setPreferredSize(new Dimension(890, altura));
        } catch (SQLException ex) {
            Logger.getLogger(ADevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cargarComboProy() {
        try {
            VideoproyectorDB proyect = new VideoproyectorDB();
            HashMap<String, String> map = proyect.devolucionCombo();             //obtiene los datos -en DB ya se comprobo que esta disponible
            Map<String, String> map1 = new TreeMap<>(map);                      //ordena el HashMap
            jComboBox1.removeAllItems();
            if(map1.isEmpty()){
                jComboBox1.setEnabled(false);
            }else{
                // agrega los datos al comboBox
                for (String s : map1.keySet()) {
                    String proy = s;
                    jComboBox1.addItem(proy);
                    System.out.println("\n- VideoProyector " + proy);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar registros de proyectores disponibles:"+ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dlgUsuario = new javax.swing.JDialog();
        pnlBackground1 = new javax.swing.JPanel();
        pnlColor = new javax.swing.JPanel();
        pnlColor1 = new javax.swing.JPanel();
        pnlFormulario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuarioVal = new javax.swing.JTextField();
        lblIcoInfo = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        pnlBtnCerrar = new javax.swing.JPanel();
        icoCerrar1 = new javax.swing.JLabel();
        lblTxtCerrar1 = new javax.swing.JLabel();
        lblInfo3 = new javax.swing.JLabel();
        lblStatsGood = new javax.swing.JLabel();
        lblStatsBad = new javax.swing.JLabel();
        pryArt = new javax.swing.JDialog();
        pnlBackground2 = new javax.swing.JPanel();
        lblTituloArt = new javax.swing.JLabel();
        lblNProy = new javax.swing.JLabel();
        btnReportarAcc = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblInfo4 = new javax.swing.JLabel();
        lblHiddenProfReportArt = new javax.swing.JLabel();
        dlgReporte = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtProf = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        lblListItems = new javax.swing.JLabel();
        btnReportar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblHiddenProfReporte = new javax.swing.JLabel();
        fallosReporte = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        txtSolicitante = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        jLabel42 = new javax.swing.JLabel();
        txtTituloR = new javax.swing.JTextField();
        lblRprt6 = new javax.swing.JLabel();
        cb4 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        cb7 = new javax.swing.JCheckBox();
        btnReporte = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        hiddenNSerie = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        pnlCabecera = new javax.swing.JPanel();
        lblIco1 = new javax.swing.JLabel();
        lblIco2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        btnMenu = new javax.swing.JToggleButton();
        btnRegresar = new javax.swing.JButton();
        panelOPC = new javax.swing.JPanel();
        ico3 = new javax.swing.JLabel();
        ico4 = new javax.swing.JLabel();
        ico5 = new javax.swing.JLabel();
        ico6 = new javax.swing.JLabel();
        ico7 = new javax.swing.JLabel();
        ico8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JPanel();
        lblIco3 = new javax.swing.JLabel();
        lblTextoDev = new javax.swing.JLabel();
        scrollContainer = new javax.swing.JScrollPane();
        pnlContenedor = new javax.swing.JPanel();
        chkBLista = new javax.swing.JCheckBox();
        layerNoSerie = new javax.swing.JLayeredPane();
        pnlNoSerie = new javax.swing.JPanel();
        barraSeparadora = new javax.swing.JPanel();
        txtNSerie = new javax.swing.JTextField();
        pnlCbNSerie = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();

        dlgUsuario.setMinimumSize(new java.awt.Dimension(581, 321));
        dlgUsuario.setModal(true);
        dlgUsuario.setUndecorated(true);
        dlgUsuario.setResizable(false);

        pnlBackground1.setBackground(new java.awt.Color(255, 103, 96));
        pnlBackground1.setMinimumSize(new java.awt.Dimension(581, 321));
        pnlBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlColor.setBackground(new java.awt.Color(158, 163, 13));
        pnlColor.setPreferredSize(new java.awt.Dimension(25, 321));

        javax.swing.GroupLayout pnlColorLayout = new javax.swing.GroupLayout(pnlColor);
        pnlColor.setLayout(pnlColorLayout);
        pnlColorLayout.setHorizontalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlColorLayout.setVerticalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlBackground1.add(pnlColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 322));

        pnlColor1.setBackground(new java.awt.Color(206, 210, 72));
        pnlColor1.setPreferredSize(new java.awt.Dimension(15, 0));

        javax.swing.GroupLayout pnlColor1Layout = new javax.swing.GroupLayout(pnlColor1);
        pnlColor1.setLayout(pnlColor1Layout);
        pnlColor1Layout.setHorizontalGroup(
            pnlColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pnlColor1Layout.setVerticalGroup(
            pnlColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlBackground1.add(pnlColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, -1, 322));

        pnlFormulario.setOpaque(false);
        pnlFormulario.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Validar Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlFormulario.add(jLabel4, gridBagConstraints);

        txtUsuarioVal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtUsuarioVal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioVal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtUsuarioVal.setMinimumSize(new java.awt.Dimension(250, 35));
        txtUsuarioVal.setPreferredSize(new java.awt.Dimension(250, 35));
        txtUsuarioVal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioValKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 20, 20, 20);
        pnlFormulario.add(txtUsuarioVal, gridBagConstraints);

        pnlBackground1.add(pnlFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 340, -1));

        lblIcoInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/More Info_22px.png"))); // NOI18N
        pnlBackground1.add(lblIcoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 285, -1, -1));

        lblInfo2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblInfo2.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo2.setText("<html>clic en pulgar arrbia para Liberar prestamo<br>clic en pulgar abajo para reportar videoproyector</html>");
        pnlBackground1.add(lblInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        pnlBtnCerrar.setBackground(new java.awt.Color(239, 239, 239));
        pnlBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnCerrarMouseExited(evt);
            }
        });
        pnlBtnCerrar.setLayout(new java.awt.GridBagLayout());

        icoCerrar1.setForeground(new java.awt.Color(231, 76, 60));
        icoCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 14, 4, 0);
        pnlBtnCerrar.add(icoCerrar1, gridBagConstraints);

        lblTxtCerrar1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblTxtCerrar1.setForeground(new java.awt.Color(231, 76, 60));
        lblTxtCerrar1.setText("Cerrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 14);
        pnlBtnCerrar.add(lblTxtCerrar1, gridBagConstraints);

        pnlBackground1.add(pnlBtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 227, -1, -1));

        lblInfo3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblInfo3.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo3.setText("Estatus del Proyector");
        pnlBackground1.add(lblInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 128, -1, -1));

        lblStatsGood.setBackground(new java.awt.Color(255, 103, 96));
        lblStatsGood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatsGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pulgarArriba-74px.png"))); // NOI18N
        lblStatsGood.setOpaque(true);
        lblStatsGood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatsGoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStatsGoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStatsGoodMouseExited(evt);
            }
        });
        pnlBackground1.add(lblStatsGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 152, 64, 64));

        lblStatsBad.setBackground(new java.awt.Color(255, 103, 96));
        lblStatsBad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pulgarAbajo-64px.png"))); // NOI18N
        lblStatsBad.setMaximumSize(new java.awt.Dimension(74, 74));
        lblStatsBad.setMinimumSize(new java.awt.Dimension(74, 74));
        lblStatsBad.setOpaque(true);
        lblStatsBad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatsBadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStatsBadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStatsBadMouseExited(evt);
            }
        });
        pnlBackground1.add(lblStatsBad, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 152, -1, -1));

        javax.swing.GroupLayout dlgUsuarioLayout = new javax.swing.GroupLayout(dlgUsuario.getContentPane());
        dlgUsuario.getContentPane().setLayout(dlgUsuarioLayout);
        dlgUsuarioLayout.setHorizontalGroup(
            dlgUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgUsuarioLayout.setVerticalGroup(
            dlgUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgUsuario.getAccessibleContext().setAccessibleParent(this);

        pryArt.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pryArt.setTitle("[Articulos]");
        pryArt.setMinimumSize(new java.awt.Dimension(320, 295));
        pryArt.setModal(true);
        pryArt.setUndecorated(true);
        pryArt.setResizable(false);

        pnlBackground2.setBackground(new java.awt.Color(195, 83, 93));
        pnlBackground2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 213, 217), 4));
        pnlBackground2.setMinimumSize(new java.awt.Dimension(320, 295));
        pnlBackground2.setPreferredSize(new java.awt.Dimension(320, 295));
        pnlBackground2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloArt.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTituloArt.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloArt.setText("<html>Articulos solicitados con el siguiente<br>Video Proyector:</html>");
        pnlBackground2.add(lblTituloArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, -1, -1));

        lblNProy.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblNProy.setForeground(new java.awt.Color(255, 255, 255));
        lblNProy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNProy.setText("lblNombreProyector");
        pnlBackground2.add(lblNProy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 320, -1));

        btnReportarAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportar-22px.png"))); // NOI18N
        btnReportarAcc.setText("Reportar!");
        btnReportarAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarAccActionPerformed(evt);
            }
        });
        pnlBackground2.add(btnReportarAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlBackground2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        pnlBackground2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 170, 90));

        lblInfo4.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo4.setText("<html><center>Para reportar más de un elemento mantenga<br>presionado la tecla CTRL y con clic izquierdo<br>seleccione los demas elementos</center></html>");
        pnlBackground2.add(lblInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 300, 50));
        pnlBackground2.add(lblHiddenProfReportArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        javax.swing.GroupLayout pryArtLayout = new javax.swing.GroupLayout(pryArt.getContentPane());
        pryArt.getContentPane().setLayout(pryArtLayout);
        pryArtLayout.setHorizontalGroup(
            pryArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(pryArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pryArtLayout.createSequentialGroup()
                    .addComponent(pnlBackground2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pryArtLayout.setVerticalGroup(
            pryArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
            .addGroup(pryArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pryArtLayout.createSequentialGroup()
                    .addComponent(pnlBackground2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dlgReporte.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReporte.setTitle("[Reporte de Artículos]");
        dlgReporte.setMinimumSize(new java.awt.Dimension(750, 420));
        dlgReporte.setModal(true);

        jPanel2.setBackground(new java.awt.Color(255, 138, 101));
        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reporte de Pérdida/Fallos sobre Artículo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 13, 720, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descripcion corta sobre el problema:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descripción de la falla o como fue perdido el artículo:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Profesor:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtTitulo.setPreferredSize(new java.awt.Dimension(280, 30));
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloKeyTyped(evt);
            }
        });
        jPanel2.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 390, 30));

        txtProf.setEditable(false);
        txtProf.setBackground(new java.awt.Color(255, 255, 255));
        txtProf.setEnabled(false);
        txtProf.setPreferredSize(new java.awt.Dimension(280, 30));
        jPanel2.add(txtProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 390, -1));

        txtDesc.setColumns(20);
        txtDesc.setLineWrap(true);
        txtDesc.setRows(5);
        txtDesc.setWrapStyleWord(true);
        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtDesc);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 390, 110));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.gray), "Artículo(s)"));

        lblListItems.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblListItems.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblListItems.setText("jLabel14");
        lblListItems.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblListItems.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        lblListItems.setMinimumSize(new java.awt.Dimension(238, 218));
        lblListItems.setPreferredSize(new java.awt.Dimension(238, 218));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 250, 270));

        btnReportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportar-22px.png"))); // NOI18N
        btnReportar.setText("Reportar");
        btnReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 345, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCancelar.setText("Limpiar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 345, -1, -1));

        lblHiddenProfReporte.setText("SoyProfe");
        jPanel2.add(lblHiddenProfReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        javax.swing.GroupLayout dlgReporteLayout = new javax.swing.GroupLayout(dlgReporte.getContentPane());
        dlgReporte.getContentPane().setLayout(dlgReporteLayout);
        dlgReporteLayout.setHorizontalGroup(
            dlgReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgReporteLayout.setVerticalGroup(
            dlgReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        fallosReporte.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        fallosReporte.setTitle("[Reportar VideoProyector]");
        fallosReporte.setMinimumSize(new java.awt.Dimension(965, 450));
        fallosReporte.setModal(true);
        fallosReporte.setUndecorated(true);
        fallosReporte.setPreferredSize(new java.awt.Dimension(965, 450));
        fallosReporte.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 138, 101));
        jPanel5.setMinimumSize(new java.awt.Dimension(940, 440));
        jPanel5.setPreferredSize(new java.awt.Dimension(940, 440));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Reporte");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 940, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray), "Formulario de Reporte"));

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel33.setText("Área Solicitante:");

        jLabel34.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel34.setText("Nombre del Solicitante:");

        jLabel35.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel35.setText("Descripción detallada del servicio solicitado o falla a reparar:");
        jLabel35.setToolTipText("");

        txtArea.setText("Departamento de Desarrollo Académico");
        txtArea.setMinimumSize(new java.awt.Dimension(370, 30));
        txtArea.setPreferredSize(new java.awt.Dimension(370, 30));

        txtSolicitante.setMinimumSize(new java.awt.Dimension(370, 30));
        txtSolicitante.setPreferredSize(new java.awt.Dimension(370, 30));

        txtDetalles.setColumns(20);
        txtDetalles.setLineWrap(true);
        txtDetalles.setRows(5);
        txtDetalles.setWrapStyleWord(true);
        txtDetalles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDetallesKeyTyped(evt);
            }
        });
        jScrollPane9.setViewportView(txtDetalles);

        jLabel36.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel36.setText("Departamento a quien se dirige la solicitud:");

        buttonGroup1.add(cb1);
        cb1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        cb1.setText("Recursos Materiales y Servicios");
        cb1.setOpaque(false);

        buttonGroup1.add(cb2);
        cb2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        cb2.setText("Mantenimiento de Equipo");
        cb2.setOpaque(false);

        buttonGroup1.add(cb3);
        cb3.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        cb3.setText("Centro de Cómputo");
        cb3.setOpaque(false);

        jLabel42.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel42.setText("Descripción corta de la falla:");

        txtTituloR.setMinimumSize(new java.awt.Dimension(370, 30));
        txtTituloR.setPreferredSize(new java.awt.Dimension(370, 30));
        txtTituloR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloRKeyTyped(evt);
            }
        });

        lblRprt6.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        lblRprt6.setText("Imprevisto:");

        buttonGroup2.add(cb4);
        cb4.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        cb4.setText("Reparación");
        cb4.setOpaque(false);

        buttonGroup2.add(cb5);
        cb5.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        cb5.setText("Mantenimiento");
        cb5.setOpaque(false);

        buttonGroup2.add(cb6);
        cb6.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        cb6.setText("Aplicar Garantía");
        cb6.setOpaque(false);

        buttonGroup2.add(cb7);
        cb7.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        cb7.setText("Dar de Baja");
        cb7.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTituloR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSolicitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel42)
                            .addComponent(cb3)
                            .addComponent(cb1)
                            .addComponent(jLabel36)
                            .addComponent(cb2)
                            .addComponent(jLabel33))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRprt6)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cb4)
                                .addGap(31, 31, 31)
                                .addComponent(cb6))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(cb5)
                                .addGap(18, 18, 18)
                                .addComponent(cb7)))
                        .addGap(255, 255, 255))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane9))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblRprt6)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb4)
                            .addComponent(cb6))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb5)
                            .addComponent(cb7))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTituloR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 880, 310));

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportar-22px.png"))); // NOI18N
        btnReporte.setText("Generar Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel5.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCancelar1.setText("Cancelar Reporte");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        hiddenNSerie.setText("NSeriePry");
        jPanel5.add(hiddenNSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, -1, -1));

        javax.swing.GroupLayout fallosReporteLayout = new javax.swing.GroupLayout(fallosReporte.getContentPane());
        fallosReporte.getContentPane().setLayout(fallosReporteLayout);
        fallosReporteLayout.setHorizontalGroup(
            fallosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 922, Short.MAX_VALUE)
        );
        fallosReporteLayout.setVerticalGroup(
            fallosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Devolución]");
        setIconImage(img.getImage());
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setMinimumSize(new java.awt.Dimension(1024, 600));
        pnlBackground.setPreferredSize(new java.awt.Dimension(1024, 600));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecera.setBackground(new java.awt.Color(1, 200, 1));
        pnlCabecera.setMinimumSize(new java.awt.Dimension(1024, 83));
        pnlCabecera.setPreferredSize(new java.awt.Dimension(1024, 83));

        lblIco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tecnm2.png"))); // NOI18N

        lblIco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sep.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hora");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha");

        labelHora.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 255, 255));
        labelHora.setText("00:00:00 PM");

        labelFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("00-00-0000");

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIco1)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(labelHora)
                .addGap(107, 107, 107)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(labelFecha)
                .addGap(36, 36, 36)
                .addComponent(lblIco2)
                .addContainerGap())
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIco1)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIco2))
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(labelHora))
                    .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(labelFecha))))
        );

        pnlBackground.add(pnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Checklist_24px.png"))); // NOI18N
        btnMenu.setMaximumSize(new java.awt.Dimension(40, 37));
        btnMenu.setMinimumSize(new java.awt.Dimension(40, 37));
        btnMenu.setPreferredSize(new java.awt.Dimension(40, 37));
        btnMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnMenuItemStateChanged(evt);
            }
        });
        pnlBackground.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back To_35px.png"))); // NOI18N
        btnRegresar.setMaximumSize(new java.awt.Dimension(40, 37));
        btnRegresar.setMinimumSize(new java.awt.Dimension(40, 37));
        btnRegresar.setPreferredSize(new java.awt.Dimension(40, 37));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlBackground.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        panelOPC.setBackground(new java.awt.Color(250, 250, 250));
        panelOPC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 173, 179), 1, true));
        panelOPC.setMinimumSize(new java.awt.Dimension(44, 376));
        panelOPC.setPreferredSize(new java.awt.Dimension(44, 376));
        panelOPC.setLayout(new java.awt.GridBagLayout());

        ico3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo_32px.png"))); // NOI18N
        ico3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        panelOPC.add(ico3, gridBagConstraints);

        ico4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registr_32px.png"))); // NOI18N
        ico4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico4, gridBagConstraints);

        ico5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prof_42px.png"))); // NOI18N
        ico5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        panelOPC.add(ico5, gridBagConstraints);

        ico6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/depart_42px.png"))); // NOI18N
        ico6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico6, gridBagConstraints);

        ico7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aul_42px.png"))); // NOI18N
        ico7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico7MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico7, gridBagConstraints);

        ico8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Video Projector_42px.png"))); // NOI18N
        ico8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico8MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico8, gridBagConstraints);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Electrical_42px.png"))); // NOI18N
        jLabel13.setToolTipText("Artículos");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 0);
        panelOPC.add(jLabel13, gridBagConstraints);

        pnlBackground.add(panelOPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, -1, -1));

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        lblTitulo.setText("Devolución");
        pnlBackground.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        lblInfo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblInfo.setText("No. de Serie del VideoProyector:");
        pnlBackground.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        btnDevolver.setBackground(new java.awt.Color(239, 239, 239));
        btnDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDevolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDevolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDevolverMouseExited(evt);
            }
        });
        btnDevolver.setLayout(new java.awt.GridBagLayout());

        lblIco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_22px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 12, 0);
        btnDevolver.add(lblIco3, gridBagConstraints);

        lblTextoDev.setBackground(new java.awt.Color(0, 191, 255));
        lblTextoDev.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTextoDev.setForeground(new java.awt.Color(0, 191, 255));
        lblTextoDev.setText("Registrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        btnDevolver.add(lblTextoDev, gridBagConstraints);

        pnlBackground.add(btnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 254, 130, -1));

        scrollContainer.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollContainer.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollContainer.setMinimumSize(new java.awt.Dimension(890, 290));
        scrollContainer.setPreferredSize(new java.awt.Dimension(890, 290));

        pnlContenedor.setBackground(new java.awt.Color(121, 129, 208));
        pnlContenedor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 9));
        scrollContainer.setViewportView(pnlContenedor);

        pnlBackground.add(scrollContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 308, -1, -1));

        chkBLista.setText("elegir de una lista");
        chkBLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBListaActionPerformed(evt);
            }
        });
        pnlBackground.add(chkBLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        layerNoSerie.setMinimumSize(new java.awt.Dimension(330, 48));
        layerNoSerie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNoSerie.setBackground(new java.awt.Color(255, 255, 255));
        pnlNoSerie.setMinimumSize(new java.awt.Dimension(330, 48));

        barraSeparadora.setBackground(new java.awt.Color(125, 119, 105));
        barraSeparadora.setMinimumSize(new java.awt.Dimension(330, 3));
        barraSeparadora.setPreferredSize(new java.awt.Dimension(330, 3));

        javax.swing.GroupLayout barraSeparadoraLayout = new javax.swing.GroupLayout(barraSeparadora);
        barraSeparadora.setLayout(barraSeparadoraLayout);
        barraSeparadoraLayout.setHorizontalGroup(
            barraSeparadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        barraSeparadoraLayout.setVerticalGroup(
            barraSeparadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        txtNSerie.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtNSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNSerie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtNSerie.setMinimumSize(new java.awt.Dimension(250, 30));
        txtNSerie.setPreferredSize(new java.awt.Dimension(250, 30));
        txtNSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNSerieKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlNoSerieLayout = new javax.swing.GroupLayout(pnlNoSerie);
        pnlNoSerie.setLayout(pnlNoSerieLayout);
        pnlNoSerieLayout.setHorizontalGroup(
            pnlNoSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(pnlNoSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlNoSerieLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlNoSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(barraSeparadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlNoSerieLayout.setVerticalGroup(
            pnlNoSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(pnlNoSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlNoSerieLayout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(txtNSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(barraSeparadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        layerNoSerie.add(pnlNoSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlCbNSerie.setBackground(new java.awt.Color(255, 255, 255));
        pnlCbNSerie.setMinimumSize(new java.awt.Dimension(330, 48));

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(330, 35));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCbNSerieLayout = new javax.swing.GroupLayout(pnlCbNSerie);
        pnlCbNSerie.setLayout(pnlCbNSerieLayout);
        pnlCbNSerieLayout.setHorizontalGroup(
            pnlCbNSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(pnlCbNSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCbNSerieLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlCbNSerieLayout.setVerticalGroup(
            pnlCbNSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(pnlCbNSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCbNSerieLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        layerNoSerie.add(pnlCbNSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlBackground.add(layerNoSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ico3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico3MouseClicked
        AlPrestamo pres = new AlPrestamo();
        pres.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico3MouseClicked

    private void ico4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico4MouseClicked
        ARegistro reg = new ARegistro();
        reg.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico4MouseClicked

    private void ico5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico5MouseClicked
        try {
            Profesor profe = new Profesor();
            profe.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AlPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ico5MouseClicked

    private void ico6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico6MouseClicked
        try {
            Departamento depart = new Departamento();
            depart.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AlPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ico6MouseClicked

    private void ico7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico7MouseClicked
        try {
            Aula aula = new Aula();
            aula.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ADevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ico7MouseClicked

    private void ico8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico8MouseClicked
        try {
            Videoproyector vid = new Videoproyector();
            vid.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ADevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ico8MouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnMenuItemStateChanged
        if (btnMenu.isSelected()) {
            panelOPC.setVisible(true);
        } else {
            panelOPC.setVisible(false);
        }
    }//GEN-LAST:event_btnMenuItemStateChanged

    private void btnDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverMouseClicked
        btnDevolver.setBackground(new Color(239,239,239));
        String noSerie = txtNSerie.getText().trim();
        revisarProyectorPrestado(noSerie);
    }//GEN-LAST:event_btnDevolverMouseClicked

    private void btnDevolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverMouseEntered
        btnDevolver.setBackground(new Color(0,191,255));
    }//GEN-LAST:event_btnDevolverMouseEntered

    private void btnDevolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverMouseExited
        btnDevolver.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_btnDevolverMouseExited

    private void pnlBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnCerrarMouseClicked
        pnlBtnCerrar.setBackground(new Color(239,239,239));
        
        dlgUsuario.setVisible(false);
        dlgUsuario.dispose();
        txtUsuarioVal.setText("");
    }//GEN-LAST:event_pnlBtnCerrarMouseClicked

    private void pnlBtnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnCerrarMouseEntered
        pnlBtnCerrar.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_pnlBtnCerrarMouseEntered

    private void pnlBtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnCerrarMouseExited
        pnlBtnCerrar.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_pnlBtnCerrarMouseExited
    public void accionarLiberacion(){//boolean estatusDevolucion, int idReporte
        String proyector = txtNSerie.getText().trim();
        String credencial = txtUsuarioVal.getText().trim();
        
        if(credencial.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe indicar una credencial!!!");
        }else{
            try {    
                //revisar que exista el videoproyector txtProyNSerie
                VideoproyectorDB profe = new VideoproyectorDB();
                if(profe.getExisteProyector(proyector)){
                        UsuarioReadDB leer = new UsuarioReadDB();
                        if (leer.getExisteUsuario(credencial)){
                            //comprobar que exisa un prestamo
                            PrestamoDB dev = new PrestamoDB();
                            if (!dev.getPrestamoActivo(proyector, 3)){
                                // generar actualizacion
                                // liberar distintos articulos
                                dev.updPrestamo(proyector, credencial);
                                new LogDB().log(credencial, "E_PRESTAMOS", 7);
                                System.out.println("\n\nEl prestamo se libero: \n-Proyector:" + proyector + "\n-Credencial: " + credencial+"\n\n");
                                pnlContenedor.removeAll();
                                pnlContenedor.repaint();
                                dibujarDevoluciones();
                                ImageIcon iconJPane = new ImageIcon("./src/imagenes/Ok.png");
                                JOptionPane.showMessageDialog(null, "El videoproyector ahora se registra como disponible", "Información", JOptionPane.INFORMATION_MESSAGE, iconJPane);
                                txtNSerie.requestFocusInWindow();
                                cargarComboProy();
                            }else{
                                JOptionPane.showMessageDialog(null, "El videoproyector indicado no fue reconocido", "Información", JOptionPane.ERROR_MESSAGE);
                            }

                        }else{
                            JOptionPane.showMessageDialog(null, "Este usuario indicado no se encuentra registrado", "Información", JOptionPane.INFORMATION_MESSAGE);
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "El videoproyector indicado no se ha prestado");
                }
                txtNSerie.setText("");
                txtUsuarioVal.setText("");
                dlgUsuario.setVisible(false);

                chkBLista.setSelected(false);
                pnlNoSerie.setVisible(true);
                pnlCbNSerie.setVisible(false);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Existe un problema al liberar proyector:\n\n"+ex);
            }
        }
    }
    private void txtNSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNSerieKeyTyped
        if (txtNSerie.getText().length() >= 20) {
            evt.consume();
        }
        
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            String noSerie = txtNSerie.getText().trim();
            revisarProyectorPrestado(noSerie);
        }
    }//GEN-LAST:event_txtNSerieKeyTyped

    public void revisarProyectorPrestado(String noSerie){
         if (!noSerie.isEmpty()){
                //comprobar que exisa un prestamo
                try{
                    PrestamoDB dev = new PrestamoDB();
                    if (dev.getPrestamoActivo(noSerie, 5)){
                        dlgUsuario.setLocationRelativeTo(pnlBackground);
                        dlgUsuario.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "El videoproyector indicado\nno tiene registro de que haya sido prestado");
                        txtNSerie.setText("");
                    }
                }catch(Exception ex){
                    System.out.println("Error al cargar si existen prestamos: " + ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Cuadro de texto vacio!!!");
            }
    }
    
    private void txtUsuarioValKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioValKeyTyped
//        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
//            accionarLiberacion();
//        }
    }//GEN-LAST:event_txtUsuarioValKeyTyped

    private void chkBListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBListaActionPerformed
        if(chkBLista.isSelected()){
            pnlNoSerie.setVisible(false);
            pnlCbNSerie.setVisible(true);
             try {
                VideoproyectorDB proy = new VideoproyectorDB();
                HashMap<String, String> map = proy.devolucionCombo();
                if(!map.isEmpty()){
                    jComboBox1.setSelectedIndex(0);
                    String proyNoSerie = map.get(jComboBox1.getSelectedItem().toString());
                    System.out.println("No_Serie videoproyector seleccionado: " + proyNoSerie);
                    txtNSerie.setText(proyNoSerie);
                }
            } catch (SQLException ex) {
                System.out.println("Error al recuperar informacion videoproyector ComboBox: " + ex);
            } catch (Exception e) {
                System.out.println("!!!!!!Error al recuperar informacion videoproyector ComboBox: " + e);
            }
        }else{
            pnlNoSerie.setVisible(true);
            pnlCbNSerie.setVisible(false);
        }
    }//GEN-LAST:event_chkBListaActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
         if(chkBLista.isSelected()){
            try {
                VideoproyectorDB proyector = new VideoproyectorDB();                         //instancia de proyector
                HashMap<String, String> map = proyector.devolucionCombo();                       //genera un hash con el noSerie y nombre del proyector
                if(!map.isEmpty()){
                    String proyNoSerie = map.get(jComboBox1.getSelectedItem().toString());     //del elemento seleccionado recupera el noSerie
                    System.out.println(".::NoSerie de Proyector seleccionado\n.::stateChanged: " + proyNoSerie);
                    txtNSerie.setText(proyNoSerie);
                }
            } catch (SQLException ex) {
                System.out.println("Error combVid al efecti statedSchanged: " + ex);
            }catch(Exception e){
                System.out.println("!!!!!!Error combVis al efectisimo statedChange: " + e);
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
         if (chkBLista.isSelected()) {
            try {
                VideoproyectorDB proy = new VideoproyectorDB();                         //instancia de proyector
                HashMap<String, String> map = proy.devolucionCombo();                       //genera un hash con el noSerie y nombre del proyector
                if(!map.isEmpty()){
                    String proyNoSerie = map.get(jComboBox1.getSelectedItem().toString());     //del elemento seleccionado recupera el noSerie
                    System.out.println(".::No_Serie proyector comboVid: " + proyNoSerie);
                    txtNSerie.setText(proyNoSerie);
                }
            } catch (SQLException ex) {
                System.out.println("Error al recuperar informacion videoproyector ComboBox: " + ex);
            }
        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
         if (chkBLista.isSelected()) {
            try {
                VideoproyectorDB proyector = new VideoproyectorDB();                         //instancia de proyector
                HashMap<String, String> map = proyector.devolucionCombo();                       //genera un hash con el noSerie y nombre del proyector
                if(!map.isEmpty()){
                    String proyNoSerie = map.get(jComboBox1.getSelectedItem().toString());     //del elemento seleccionado recupera el noSerie
                    System.out.println(".::NoSerie de Proyector seleccionado\n.::focusLost: " + proyNoSerie);
                    txtNSerie.setText(proyNoSerie);
                }
            } catch (SQLException ex) {
                System.out.println("Error combVid al perder focus: " + ex);
            }
        }
    }//GEN-LAST:event_jComboBox1FocusLost

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        pryArt.setVisible(false);
        pryArt.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnReportarAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarAccActionPerformed
        accesorios.clear();
        List<String> list = new ArrayList<String>();
        list = jList1.getSelectedValuesList();
        String[] arr = list.stream().toArray(String[]::new);
        System.out.println("Arr: " + Arrays.toString(arr));
        if(arr.length > 0){
            String bulletList = "<html><ul>";
            for(String i: arr){ bulletList += "<li>"+i+"</li><br>"; accesorios.add(i); }
            bulletList += "</ul></html>";
            lblListItems.setText(bulletList);

            lblHiddenProfReporte.setText(lblHiddenProfReportArt.getText());
            try{
            String[] profe = new ProfesorDB().getProfesor(lblHiddenProfReportArt.getText());
            txtProf.setText(profe[2] + " " + profe[3] + " " +profe[4]);
            }catch(SQLException ex){ System.out.println("Error al recuperar nombre del profesor en reporte: " + ex); }
            
            txtTitulo.setTransferHandler(null);
            txtDesc.setTransferHandler(null);
            dlgReporte.setLocationRelativeTo(this);
            dlgReporte.setVisible(true);
            pryArt.setVisible(false);
            pryArt.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Al menos debe seleccionar un articulo para generar el reporte");
        }
    }//GEN-LAST:event_btnReportarAccActionPerformed

    private void btnReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarActionPerformed
        String profe = lblHiddenProfReporte.getText();
        String titulo = txtTitulo.getText().trim();
        String detalles = txtDesc.getText().trim();
        int i = 0;
        if(!titulo.isEmpty() && !detalles.isEmpty()){
            String[] acc = new String[accesorios.size()];
            Iterator<String> iterar = accesorios.iterator();
            while(iterar.hasNext()){ acc[i] = iterar.next(); i++; }
            
            Calendar c = Calendar.getInstance();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm");
            String fecha = dateFormat.format(c.getTime());
            System.out.println("Profe: " + profe + "\nDescCorta: " + titulo + "\nDetalles: " + detalles + "\nArticulos: " + Arrays.toString(acc)+ "\nFecha: " + fecha);
            
            JOptionPane.showMessageDialog(this, "Reporte Realizado!\nSe descartaran del inventario los artículos que ha indicado","Información", JOptionPane.INFORMATION_MESSAGE);
            try{
            AccesorioDB accDB = new AccesorioDB();
            int[] accesorioID = new int[acc.length];
            int j = 0;
            for(String ac : acc){
                accesorioID[j] = accDB.getAccesorioID(ac);
                j++;
            }
            accDB.reporteAcc(profe, titulo, detalles, accesorioID);
            
            }catch(SQLException ex){ System.out.println("Error de tabla accesorio como reporte: " + ex); }
                    
            
            dlgReporte.setVisible(false);
            dlgReporte.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Recuerde completar todos los campos");
        }
    }//GEN-LAST:event_btnReportarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtTitulo.setText("");
        txtDesc.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyTyped
        if (txtTitulo.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTituloKeyTyped

    private void txtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyTyped
        if (txtDesc.getText().length() >= 450) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDescKeyTyped

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        Articulo art = new Articulo();
        art.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void lblStatsGoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatsGoodMouseClicked
        lblStatsGood.setBackground(new Color(255,103,96));
        accionarLiberacion();
    }//GEN-LAST:event_lblStatsGoodMouseClicked

    private void lblStatsGoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatsGoodMouseEntered
        lblStatsGood.setBackground(new Color(238,238,238));
    }//GEN-LAST:event_lblStatsGoodMouseEntered

    private void lblStatsGoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatsGoodMouseExited
        lblStatsGood.setBackground(new Color(255,103,96));
    }//GEN-LAST:event_lblStatsGoodMouseExited

    private void lblStatsBadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatsBadMouseClicked
        lblStatsBad.setBackground(new Color(255,103,96));
        String credncl = txtUsuarioVal.getText().trim();
        String proyector = txtNSerie.getText().trim();
        if(!credncl.isEmpty()){
            try {    
                //revisar que exista el videoproyector txtProyNSerie
                VideoproyectorDB profe = new VideoproyectorDB();
                if(profe.getExisteProyector(proyector)){
                        UsuarioReadDB leer = new UsuarioReadDB();
                        if (leer.getExisteUsuario(credncl)){
                            hiddenNSerie.setText(proyector);
                            fallosReporte.setLocationRelativeTo(pnlBackground);
                            fallosReporte.setVisible(true);
                        }else{JOptionPane.showMessageDialog(this, "El usuario indicado no se encuentra registrado");}
                }else{JOptionPane.showMessageDialog(this, "El videoproyector indicado no existe");}
            }catch(SQLException e){System.out.println("Error al cargar reigstros de  db:"+e);}
        }else{
            JOptionPane.showMessageDialog(this, "Es importante indique su credenial");
        }
    }//GEN-LAST:event_lblStatsBadMouseClicked

    private void lblStatsBadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatsBadMouseEntered
        lblStatsBad.setBackground(new Color(238,238,238));
    }//GEN-LAST:event_lblStatsBadMouseEntered

    private void lblStatsBadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatsBadMouseExited
        lblStatsBad.setBackground(new Color(255,103,96));
    }//GEN-LAST:event_lblStatsBadMouseExited

    private void txtDetallesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDetallesKeyTyped
        if (txtDetalles.getText().length() >= 450) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDetallesKeyTyped

    private void txtTituloRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloRKeyTyped
        if (txtTituloR.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTituloRKeyTyped

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        String proyector = txtNSerie.getText().trim();
        String credencial = txtUsuarioVal.getText().trim();
        String titulo = txtTituloR.getText().trim();
        String nombreEncargado = txtSolicitante.getText().trim();
        String area = txtArea.getText().trim();
        String deptoReparador = "a";
        String imprevisto = "a";
        String detalles = txtDetalles.getText().trim();
        
        if(!area.isEmpty() && !nombreEncargado.isEmpty() && !detalles.isEmpty() && !titulo.isEmpty()){
            if((cb1.isSelected() || cb2.isSelected() || cb3.isSelected()) && (cb4.isSelected() || cb5.isSelected() || cb6.isSelected() || cb7.isSelected())){
                //deptoReparador
                if(cb1.isSelected()){ deptoReparador = "a";}
                else if(cb2.isSelected()){ deptoReparador = "b";}
                else if(cb3.isSelected()){ deptoReparador = "c";}
                //imprevisto
                if(cb4.isSelected()){ imprevisto = "a";}
                else if(cb5.isSelected()){ imprevisto = "b";}
                else if(cb6.isSelected()){ imprevisto = "c";}
                else if(cb7.isSelected()){ imprevisto = "d";}
                String[] datos = {titulo, nombreEncargado, area, deptoReparador, imprevisto, detalles};
                String[] reporteDtos = {area, nombreEncargado, detalles, deptoReparador, proyector};

                try {
                    VideoproyectorDB pry = new VideoproyectorDB();
                    GenerarReportes genR = new GenerarReportes();
                    
                    PrestamoDB pres = new PrestamoDB();

                    pres.updPrestamoConReporte(proyector, credencial, datos);//noSerie, idUsuario, datosR
                    
                    genR.getReporteFalloPry(reporteDtos);
                    new LogDB().log(credencial, "E_PRESTAMOS", 7);
                    
                    
                    System.out.println("El prestamo se libero!: \n-Proyector:" + proyector + "\n-Credencial: " + credencial);
                    pnlContenedor.removeAll();
                    pnlContenedor.repaint();
                    dibujarDevoluciones();
                    ImageIcon iconJPane = new ImageIcon("./src/imagenes/Ok.png");
                    JOptionPane.showMessageDialog(null, "El videoproyector ahora se registra como disponible", "Información", JOptionPane.INFORMATION_MESSAGE, iconJPane);
                    txtNSerie.requestFocusInWindow();
                    cargarComboProy();

                    txtNSerie.setText("");
                    txtUsuarioVal.setText("");
                    dlgUsuario.setVisible(false);

                    chkBLista.setSelected(false);
                    pnlNoSerie.setVisible(true);
                    pnlCbNSerie.setVisible(false);
                    
                    fallosReporte.setVisible(false);
                    fallosReporte.dispose();
                } catch (SQLException ex) {
                    System.out.println("Error al crear registro de prestamo en videoproyector btnReporte: " + ex);
                }
            }else{JOptionPane.showMessageDialog(null, "Recuerde llenar todo el formulario"); clearReport();}
        }else{
            JOptionPane.showMessageDialog(null, "Recuerde llenar todo el formulario"); clearReport();
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        clearReport();
        fallosReporte.setVisible(false);
        fallosReporte.dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    public void clearReport(){
        txtArea.setText("Departamento de Desarrollo Académico");
        txtSolicitante.setText("");
        txtDetalles.setText("");
        txtTituloR.setText("");
        jLabel31.setText("Reporte de Fallos");
        
        cb1.setSelected(false);
        cb2.setSelected(false);
        cb3.setSelected(false);
        
        cb4.setSelected(false);
        cb5.setSelected(false);
        cb6.setSelected(false);
        cb7.setSelected(false);
    }
    
    public void miPanel(String[] datos) throws SQLException{
        JPanel pnlVidDetalles = new JPanel();
        GridBagConstraints c = new GridBagConstraints();
        
        pnlVidDetalles.setOpaque(false);
        pnlVidDetalles.setForeground(new Color(255, 255, 255));
        pnlVidDetalles.setPreferredSize(new Dimension(200, 270));
        pnlVidDetalles.setLayout(new GridBagLayout());
        pnlVidDetalles.setBorder(new RoundedBorder(25));
        
        JLabel vid = new JLabel("Videoproyector");
        vid.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); 
        vid.setForeground(new java.awt.Color(255, 255, 255));
        c.insets = new Insets(0, 30, 15, 0);
        pnlVidDetalles.add(vid, c);
        
        JLabel vidNom = new JLabel();
        vidNom.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); 
        vidNom.setForeground(new java.awt.Color(255, 255, 255));
        c = new GridBagConstraints();
        c.anchor = GridBagConstraints.LINE_START;
        c.insets = new Insets(0, 10, 15, 0);
        pnlVidDetalles.add(vidNom, c);
        
        JPanel pnlSeparador = new JPanel();
        pnlSeparador.setBackground(new Color(241, 245, 248));
        pnlSeparador.setMinimumSize(new Dimension(240, 2));
        pnlSeparador.setPreferredSize(new Dimension(240, 2));
        
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 2;
        pnlVidDetalles.add(pnlSeparador, c);
        
        JPanel pnlBody = new JPanel();
        pnlBody.setOpaque(false);
        pnlBody.setLayout(new GridBagLayout());

        JLabel lblProfe = new JLabel("Profesor:");
        lblProfe.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        lblProfe.setForeground(new Color(255, 255, 255));
        c = new GridBagConstraints();
        c.anchor = GridBagConstraints.WEST;
        c.insets = new Insets(12, 0, 0, 0);
        pnlBody.add(lblProfe, c);
        
        
        JLabel lblDtsProfe = new JLabel();
        lblDtsProfe.setFont(new java.awt.Font("Verdana", 0, 9));
        lblDtsProfe.setForeground(new Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 1;
        c.insets = new Insets(2, 0, 2, 2);
        pnlBody.add(lblDtsProfe, c);
        
        JLabel lblFecha = new JLabel("Solicitado a las:");
        lblFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); 
        lblFecha.setForeground(new Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 2;
        c.anchor = GridBagConstraints.WEST;
        c.insets = new java.awt.Insets(7, 0, 0, 0);
        pnlBody.add(lblFecha, c);
        
        JLabel lblDtsFecha = new JLabel();
        lblDtsFecha.setFont(new java.awt.Font("Verdana", 0, 9));
        lblDtsFecha.setForeground(new java.awt.Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 3;
        c.insets = new Insets(7, 0, 7, 0);
        pnlBody.add(lblDtsFecha, c);
        
        JLabel lblAula = new JLabel("Aula:");
        lblAula.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        lblAula.setForeground(new Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 4;
        c.anchor = GridBagConstraints.WEST;
        c.insets = new Insets(7, 0, 0, 0);
        pnlBody.add(lblAula, c);
        
        JLabel lblDtsAula = new JLabel();
        lblDtsAula.setFont(new java.awt.Font("Verdana", 0, 9));
        lblDtsAula.setForeground(new Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 5;
        c.insets = new Insets(2, 0, 2, 0);
        pnlBody.add(lblDtsAula, c);
        
        JLabel lblDepto = new JLabel("Departamento de:");
        lblDepto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblDepto.setForeground(new java.awt.Color(255, 255, 255));
        lblDepto.setText("Departamento de:");
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 6;
        c.anchor = java.awt.GridBagConstraints.WEST;
        c.insets = new java.awt.Insets(7, 0, 0, 0);
        pnlBody.add(lblDepto, c);

        JLabel lblDtsDepto = new JLabel();
        lblDtsDepto.setFont(new java.awt.Font("Verdana", 0, 9)); // NOI18N
        lblDtsDepto.setForeground(new java.awt.Color(255, 255, 255));
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 7;
        c.insets = new java.awt.Insets(8, 0, 5, 0);
        pnlBody.add(lblDtsDepto, c);
        
        JButton btnArt = new JButton("-Articulos-");
        btnArt.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 8;
        c.insets = new Insets(4, 0, 0, 0);
        pnlBody.add(btnArt, c);
        
        c = new java.awt.GridBagConstraints();
        c.gridx = 0;
        c.gridy = 2;
        c.gridwidth = 2;
        
        //datos
        String[] profe = new ProfesorDB().getProfesor(datos[4]);
        String [] accesoriosAr = new AccesorioDB().getAccDeProf(datos[4]);
        String pryNom = new VideoproyectorDB().getProyector(new VideoproyectorDB().getProyectorNoSerie(datos[3]))[1];
        
        vidNom.setText(pryNom);
        lblDtsProfe.setText("<html>" + profe[2] + "<br>" + profe[3] + " " +profe[4] + "</html>");
        lblDtsFecha.setText(datos[6].substring(0,16));
        lblDtsAula.setText(new AulaDB().getAula(Integer.parseInt(datos[5])) );
        lblDtsDepto.setText(new DepartamentoDB().getDepartamento(Integer.parseInt(profe[1]))[0]);
        
        if(accesoriosAr.length > 0){
            String acc = Arrays.toString(accesoriosAr).replace("[", "").replace("]", "").replaceAll(",", "<br>");
            setToolTipRecursively(pnlVidDetalles, "<html><b>Articulos solicitados con <i>" + pryNom +"</i>:</b><br>" + acc + "</html>");
            btnArt.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) { 
                    lblNProy.setText(pryNom);
                    DefaultListModel<String> listModel = new DefaultListModel<>();
                    for(String miAcc : accesoriosAr){
                        listModel.addElement(miAcc);
                    }
                    jList1.setModel(listModel);
                    // mostrar dialog
                    lblHiddenProfReportArt.setText(datos[4]);
                    pryArt.setLocationRelativeTo(pnlBackground);
                    pryArt.setVisible(true);
                }
            });
        }else{
            btnArt.setEnabled(false);
        }
        
        pnlVidDetalles.add(pnlBody, c);
        pnlVidDetalles.revalidate();
        pnlVidDetalles.repaint();
        pnlContenedor.add(pnlVidDetalles); //añade todo el jpanel al panel principal este jPanel5 se encuentra dentro del jScrolPane
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }
    
    public static void setToolTipRecursively(javax.swing.JComponent c, String text) {

    c.setToolTipText(text);
    ToolTipManager.sharedInstance().setInitialDelay(0);
    for (java.awt.Component cc : c.getComponents())
        if (cc instanceof javax.swing.JComponent)
            setToolTipRecursively((javax.swing.JComponent) cc, text);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADevolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSeparadora;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel btnDevolver;
    private javax.swing.JToggleButton btnMenu;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReportar;
    private javax.swing.JButton btnReportarAcc;
    private javax.swing.JButton btnReporte;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox cb7;
    private javax.swing.JCheckBox chkBLista;
    private javax.swing.JDialog dlgReporte;
    private javax.swing.JDialog dlgUsuario;
    private javax.swing.JDialog fallosReporte;
    private javax.swing.JLabel hiddenNSerie;
    private javax.swing.JLabel ico3;
    private javax.swing.JLabel ico4;
    private javax.swing.JLabel ico5;
    private javax.swing.JLabel ico6;
    private javax.swing.JLabel ico7;
    private javax.swing.JLabel ico8;
    private javax.swing.JLabel icoCerrar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLayeredPane layerNoSerie;
    private javax.swing.JLabel lblHiddenProfReportArt;
    private javax.swing.JLabel lblHiddenProfReporte;
    private javax.swing.JLabel lblIco1;
    private javax.swing.JLabel lblIco2;
    private javax.swing.JLabel lblIco3;
    private javax.swing.JLabel lblIcoInfo;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfo3;
    private javax.swing.JLabel lblInfo4;
    private javax.swing.JLabel lblListItems;
    private javax.swing.JLabel lblNProy;
    private javax.swing.JLabel lblRprt6;
    private javax.swing.JLabel lblStatsBad;
    private javax.swing.JLabel lblStatsGood;
    private javax.swing.JLabel lblTextoDev;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloArt;
    private javax.swing.JLabel lblTxtCerrar1;
    private javax.swing.JPanel panelOPC;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBackground1;
    private javax.swing.JPanel pnlBackground2;
    private javax.swing.JPanel pnlBtnCerrar;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlCbNSerie;
    private javax.swing.JPanel pnlColor;
    private javax.swing.JPanel pnlColor1;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlNoSerie;
    private javax.swing.JDialog pryArt;
    private javax.swing.JScrollPane scrollContainer;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JTextField txtNSerie;
    private javax.swing.JTextField txtProf;
    private javax.swing.JTextField txtSolicitante;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTituloR;
    private javax.swing.JTextField txtUsuarioVal;
    // End of variables declaration//GEN-END:variables
}
