/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyector;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import proyector.dataBase.crud.AulaDB;
import proyector.dataBase.crud.PrestamoDB;

/**
 *
 * @author JuanGSot
 */
public class Aula extends javax.swing.JFrame {
String date = new SimpleDateFormat("dd-MM-yyyy").format(new Date());
ImageIcon img = new ImageIcon("./src/imagenes/logo-adm.png");
ImageIcon addW = new ImageIcon("./src/imagenes/Add New_36pxW.png");
ImageIcon ersW = new ImageIcon("./src/imagenes/Erase_36pxW.png");
ImageIcon updW = new ImageIcon("./src/imagenes/Edit File_36pxW.png");
ImageIcon add = new ImageIcon("./src/imagenes/Add New_36px.png");
ImageIcon ers = new ImageIcon("./src/imagenes/Erase_36px.png");
ImageIcon upd = new ImageIcon("./src/imagenes/Edit File_36px.png");
//AulaDB aula = new AulaDB();
    /**
     * Creates new form Aula
     */
    public Aula() throws SQLException {
        initComponents();
        
        getTable();
        agregarAulaCombo();
        ordenarDatosTabla();
        pnlFormulario.setVisible(false);
        pnlCombo.setVisible(true);
        panelOPC.setVisible(false);
        
        
        labelFecha.setText(date);
        Timer timer = new Timer(500, (ActionEvent e) -> {
            reloj();
        });
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.setInitialDelay(0);
        timer.start();
    }

    /**
     * Se encarga de colocar la hora con un formato especifico
     */
    public void reloj(){
        labelHora.setText(new SimpleDateFormat("hh:mm:ss a").format(new Date()));
    }

    /**
     * Introduce la informacion en un jTable indicado
     * @throws SQLException 
     */
    public void getTable() throws SQLException{
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //System.out.println("getTable"); //cada vez que es llamado el metodo se mostrara
        String[] cols = {"id", "Aula"};
        int count = aula.getRegistros();
        String[][] data = new String[count][2];
        for (int i = 0; i < count; i++){
            for (int j = 0; j < 2; j++) {
                data[i][j] = aula.getAulas()[i][j];
            }
        }
        model.setDataVector(data, cols);
    }
    
    /**
     * Se hace uso de un comboBox con informacion oculta
     * este metodo agrega datos a un ComboBox para elminar el registro por su id
     */
    public void agregarAulaCombo() throws SQLException{
        HashMap<String, Integer> map = aula.primerCombo();              //obtiene los datos 
        Map<String, Integer> map1 = new TreeMap<String, Integer>(map);  //ordena el HashMap
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        for(String s: map1.keySet()){   // agrega los datos al comboBox
            jComboBox1.addItem(s);
            jComboBox2.addItem(s);
        }
    }

    /**
     * Permite ordenar solo la columna de aulas en el jTable indicado
     */
    public void ordenarDatosTabla(){
        jTable1.setAutoCreateRowSorter(true);
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        sorter.sort();
        sorter.setSortable(0, false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dlgNuevo = new javax.swing.JDialog();
        pnlBkNuevo = new javax.swing.JPanel();
        lblCabecera1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnlFormularioCrear = new javax.swing.JPanel();
        txtAula = new javax.swing.JTextField();
        barraSeparadora1 = new javax.swing.JPanel();
        lblAulaNom = new javax.swing.JLabel();
        dlgBorrar = new javax.swing.JDialog();
        pnlBkBorrar = new javax.swing.JPanel();
        lblCabecera2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnEliminarRegistro = new javax.swing.JButton();
        btnCerrar1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dlgActualizar = new javax.swing.JDialog();
        pnlBkActualizar = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblCabecera3 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCerrar2 = new javax.swing.JButton();
        jLydPane1 = new javax.swing.JLayeredPane();
        pnlCombo = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnActualizarComb = new javax.swing.JButton();
        pnlFormulario = new javax.swing.JPanel();
        lblAulaNom1 = new javax.swing.JLabel();
        txtAulaNuevo = new javax.swing.JTextField();
        bkAulas = new javax.swing.JPanel();
        pnlCabecera = new javax.swing.JPanel();
        ico1 = new javax.swing.JLabel();
        ico2 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        btnMenu = new javax.swing.JToggleButton();
        panelOPC = new javax.swing.JPanel();
        ico3 = new javax.swing.JLabel();
        ico4 = new javax.swing.JLabel();
        ico5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Aulas = new javax.swing.JLabel();
        pnlBtnNuevo = new javax.swing.JPanel();
        icoN = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlBtnBorrar = new javax.swing.JPanel();
        icoB = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlBtnActualizar = new javax.swing.JPanel();
        icoA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        dlgNuevo.setLocation(new java.awt.Point(0, 0));
        dlgNuevo.setMinimumSize(new java.awt.Dimension(600, 267));
        dlgNuevo.setModal(true);
        dlgNuevo.setUndecorated(true);
        dlgNuevo.setResizable(false);

        pnlBkNuevo.setBackground(new java.awt.Color(250, 250, 250));
        pnlBkNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlBkNuevo.setMaximumSize(new java.awt.Dimension(600, 267));
        pnlBkNuevo.setMinimumSize(new java.awt.Dimension(600, 267));
        pnlBkNuevo.setPreferredSize(new java.awt.Dimension(600, 267));

        lblCabecera1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblCabecera1.setText("Nuevo Registro");

        btnGuardar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_22px.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnGuardarKeyTyped(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(1, 200, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(12, 193, 243));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlFormularioCrear.setOpaque(false);
        pnlFormularioCrear.setLayout(new java.awt.GridBagLayout());

        txtAula.setBackground(new java.awt.Color(250, 250, 250));
        txtAula.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtAula.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 5, 0, 1));
        txtAula.setMinimumSize(new java.awt.Dimension(200, 30));
        txtAula.setPreferredSize(new java.awt.Dimension(200, 30));
        txtAula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAulaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(33, 30, 0, 30);
        pnlFormularioCrear.add(txtAula, gridBagConstraints);

        barraSeparadora1.setBackground(new java.awt.Color(0, 0, 0));
        barraSeparadora1.setMinimumSize(new java.awt.Dimension(200, 3));
        barraSeparadora1.setPreferredSize(new java.awt.Dimension(200, 3));

        javax.swing.GroupLayout barraSeparadora1Layout = new javax.swing.GroupLayout(barraSeparadora1);
        barraSeparadora1.setLayout(barraSeparadora1Layout);
        barraSeparadora1Layout.setHorizontalGroup(
            barraSeparadora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadora1Layout.setVerticalGroup(
            barraSeparadora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlFormularioCrear.add(barraSeparadora1, gridBagConstraints);

        lblAulaNom.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblAulaNom.setText("Nombre del Aula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        pnlFormularioCrear.add(lblAulaNom, gridBagConstraints);

        javax.swing.GroupLayout pnlBkNuevoLayout = new javax.swing.GroupLayout(pnlBkNuevo);
        pnlBkNuevo.setLayout(pnlBkNuevoLayout);
        pnlBkNuevoLayout.setHorizontalGroup(
            pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblCabecera1))
                    .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnGuardar)
                        .addGap(101, 101, 101)
                        .addComponent(btnCerrar))
                    .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(pnlFormularioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(531, 531, 531))
        );
        pnlBkNuevoLayout.setVerticalGroup(
            pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCabecera1)
                .addGap(37, 37, 37)
                .addComponent(pnlFormularioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCerrar))
                .addGap(40, 40, 40))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dlgNuevoLayout = new javax.swing.GroupLayout(dlgNuevo.getContentPane());
        dlgNuevo.getContentPane().setLayout(dlgNuevoLayout);
        dlgNuevoLayout.setHorizontalGroup(
            dlgNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgNuevoLayout.setVerticalGroup(
            dlgNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgNuevo.getAccessibleContext().setAccessibleParent(this);

        dlgBorrar.setMinimumSize(new java.awt.Dimension(606, 274));
        dlgBorrar.setModal(true);
        dlgBorrar.setUndecorated(true);
        dlgBorrar.setResizable(false);

        pnlBkBorrar.setBackground(new java.awt.Color(255, 127, 80));
        pnlBkBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        pnlBkBorrar.setMinimumSize(new java.awt.Dimension(606, 274));
        pnlBkBorrar.setPreferredSize(new java.awt.Dimension(606, 274));

        lblCabecera2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblCabecera2.setForeground(new java.awt.Color(255, 255, 255));
        lblCabecera2.setText("Borrar Registro");

        jPanel6.setBackground(new java.awt.Color(12, 193, 243));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBox1.setMaximumRowCount(10);
        jComboBox1.setMinimumSize(new java.awt.Dimension(260, 35));
        jComboBox1.setPreferredSize(new java.awt.Dimension(260, 35));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnEliminarRegistro.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEliminarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Waste_24px.png"))); // NOI18N
        btnEliminarRegistro.setText("Eliminar");
        btnEliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRegistroActionPerformed(evt);
            }
        });

        btnCerrar1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCerrar1.setText("Cerrar");
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Para eliminar un registro indique cual debe ser eliminado");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/More Info_22px.png"))); // NOI18N

        javax.swing.GroupLayout pnlBkBorrarLayout = new javax.swing.GroupLayout(pnlBkBorrar);
        pnlBkBorrar.setLayout(pnlBkBorrarLayout);
        pnlBkBorrarLayout.setHorizontalGroup(
            pnlBkBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBkBorrarLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBkBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBkBorrarLayout.createSequentialGroup()
                        .addGroup(pnlBkBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBkBorrarLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBkBorrarLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(lblCabecera2))
                            .addGroup(pnlBkBorrarLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnEliminarRegistro)
                                .addGap(109, 109, 109)
                                .addComponent(btnCerrar1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBkBorrarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(23, 23, 23))))
        );
        pnlBkBorrarLayout.setVerticalGroup(
            pnlBkBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBkBorrarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblCabecera2)
                .addGap(29, 29, 29)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlBkBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar1)
                    .addComponent(btnEliminarRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlBkBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout dlgBorrarLayout = new javax.swing.GroupLayout(dlgBorrar.getContentPane());
        dlgBorrar.getContentPane().setLayout(dlgBorrarLayout);
        dlgBorrarLayout.setHorizontalGroup(
            dlgBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgBorrarLayout.setVerticalGroup(
            dlgBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgBorrar.getAccessibleContext().setAccessibleParent(this);

        dlgActualizar.setMinimumSize(new java.awt.Dimension(635, 316));
        dlgActualizar.setModal(true);
        dlgActualizar.setUndecorated(true);
        dlgActualizar.setResizable(false);

        pnlBkActualizar.setBackground(new java.awt.Color(0, 191, 255));
        pnlBkActualizar.setMinimumSize(new java.awt.Dimension(635, 316));
        pnlBkActualizar.setPreferredSize(new java.awt.Dimension(635, 316));
        pnlBkActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(253, 184, 19));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlBkActualizar.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 320));

        jPanel9.setBackground(new java.awt.Color(1, 200, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlBkActualizar.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 10, 321));

        jPanel10.setBackground(new java.awt.Color(152, 205, 50));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlBkActualizar.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 321));

        lblCabecera3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblCabecera3.setForeground(new java.awt.Color(255, 255, 255));
        lblCabecera3.setText("Actualizar Registro");
        pnlBkActualizar.add(lblCabecera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        btnActualizar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pencil_22px.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        pnlBkActualizar.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        btnCerrar2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCerrar2.setText("Cerrar");
        btnCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar2ActionPerformed(evt);
            }
        });
        pnlBkActualizar.add(btnCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLydPane1.setMinimumSize(new java.awt.Dimension(365, 135));

        pnlCombo.setBackground(new java.awt.Color(0, 191, 255));
        pnlCombo.setLayout(new java.awt.GridBagLayout());

        jComboBox2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBox2.setMaximumRowCount(10);
        jComboBox2.setMinimumSize(new java.awt.Dimension(240, 35));
        jComboBox2.setPreferredSize(new java.awt.Dimension(240, 35));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 50);
        pnlCombo.add(jComboBox2, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Seleccione el registro a actualizar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 8, 0);
        pnlCombo.add(jLabel14, gridBagConstraints);

        btnActualizarComb.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnActualizarComb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pencil_22px.png"))); // NOI18N
        btnActualizarComb.setText("Actualizar");
        btnActualizarComb.setMargin(new java.awt.Insets(1, 12, 1, 12));
        btnActualizarComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCombActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        pnlCombo.add(btnActualizarComb, gridBagConstraints);

        pnlFormulario.setBackground(new java.awt.Color(0, 191, 255));
        pnlFormulario.setLayout(new java.awt.GridBagLayout());

        lblAulaNom1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAulaNom1.setForeground(new java.awt.Color(255, 255, 255));
        lblAulaNom1.setText("Nombre del Aula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 0, 0);
        pnlFormulario.add(lblAulaNom1, gridBagConstraints);

        txtAulaNuevo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtAulaNuevo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 5, 1, 1));
        txtAulaNuevo.setMinimumSize(new java.awt.Dimension(200, 30));
        txtAulaNuevo.setPreferredSize(new java.awt.Dimension(200, 30));
        txtAulaNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAulaNuevoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(30, 15, 5, 15);
        pnlFormulario.add(txtAulaNuevo, gridBagConstraints);

        jLydPane1.setLayer(pnlCombo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLydPane1.setLayer(pnlFormulario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLydPane1Layout = new javax.swing.GroupLayout(jLydPane1);
        jLydPane1.setLayout(jLydPane1Layout);
        jLydPane1Layout.setHorizontalGroup(
            jLydPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jLydPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLydPane1Layout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(pnlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 30, Short.MAX_VALUE)))
            .addGroup(jLydPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLydPane1Layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );
        jLydPane1Layout.setVerticalGroup(
            jLydPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(jLydPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLydPane1Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(pnlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
            .addGroup(jLydPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLydPane1Layout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 40, Short.MAX_VALUE)))
        );

        pnlBkActualizar.add(jLydPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 400, -1));

        javax.swing.GroupLayout dlgActualizarLayout = new javax.swing.GroupLayout(dlgActualizar.getContentPane());
        dlgActualizar.getContentPane().setLayout(dlgActualizarLayout);
        dlgActualizarLayout.setHorizontalGroup(
            dlgActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgActualizarLayout.setVerticalGroup(
            dlgActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgActualizar.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Aulas]");
        setIconImage(img.getImage());
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setResizable(false);

        bkAulas.setBackground(new java.awt.Color(255, 255, 255));
        bkAulas.setMinimumSize(new java.awt.Dimension(1024, 600));
        bkAulas.setPreferredSize(new java.awt.Dimension(1024, 600));
        bkAulas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecera.setBackground(new java.awt.Color(1, 200, 1));
        pnlCabecera.setMinimumSize(new java.awt.Dimension(1024, 83));
        pnlCabecera.setPreferredSize(new java.awt.Dimension(1024, 83));

        ico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tecnm2.png"))); // NOI18N

        ico2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sep.png"))); // NOI18N

        lblHora.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("Hora");

        labelHora.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 255, 255));
        labelHora.setText("00:00:00 PM");

        lblFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha");

        labelFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("00-00-0000");

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ico1)
                .addGap(36, 36, 36)
                .addComponent(lblHora)
                .addGap(20, 20, 20)
                .addComponent(labelHora)
                .addGap(107, 107, 107)
                .addComponent(lblFecha)
                .addGap(20, 20, 20)
                .addComponent(labelFecha)
                .addGap(36, 36, 36)
                .addComponent(ico2))
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addComponent(ico1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHora)
                            .addComponent(labelHora)
                            .addComponent(lblFecha)
                            .addComponent(labelFecha)))
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ico2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bkAulas.add(pnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Checklist_24px.png"))); // NOI18N
        btnMenu.setFocusPainted(false);
        btnMenu.setMaximumSize(new java.awt.Dimension(40, 37));
        btnMenu.setMinimumSize(new java.awt.Dimension(40, 37));
        btnMenu.setPreferredSize(new java.awt.Dimension(40, 37));
        btnMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnMenuItemStateChanged(evt);
            }
        });
        bkAulas.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        panelOPC.setBackground(new java.awt.Color(250, 250, 250));
        panelOPC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 173, 179), 1, true));
        panelOPC.setLayout(new java.awt.GridBagLayout());

        ico3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo_32px.png"))); // NOI18N
        ico3.setToolTipText("Prestamo");
        ico3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        panelOPC.add(ico3, gridBagConstraints);

        ico4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/devolu_32px.png"))); // NOI18N
        ico4.setToolTipText("Devolución");
        ico4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico4, gridBagConstraints);

        ico5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registr_32px.png"))); // NOI18N
        ico5.setToolTipText("Registros");
        ico5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico5, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prof_42px.png"))); // NOI18N
        jLabel1.setToolTipText("Profesores");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        panelOPC.add(jLabel1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/depart_42px.png"))); // NOI18N
        jLabel2.setToolTipText("Departamentos");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(jLabel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Video Projector_42px.png"))); // NOI18N
        jLabel3.setToolTipText("Videoproyectores");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(jLabel3, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Electrical_42px.png"))); // NOI18N
        jLabel4.setToolTipText("Artículos");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 0);
        panelOPC.add(jLabel4, gridBagConstraints);

        bkAulas.add(panelOPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, -1, -1));

        Aulas.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Aulas.setText("Aulas");
        bkAulas.add(Aulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 112, -1, -1));

        pnlBtnNuevo.setBackground(new java.awt.Color(239, 239, 239));
        pnlBtnNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        pnlBtnNuevo.setMaximumSize(new java.awt.Dimension(100, 100));
        pnlBtnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnNuevoMouseExited(evt);
            }
        });
        pnlBtnNuevo.setLayout(new java.awt.GridBagLayout());

        icoN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add New_36px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(13, 32, 0, 32);
        pnlBtnNuevo.add(icoN, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 191, 255));
        jLabel8.setText("Nuevo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        pnlBtnNuevo.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 191, 255));
        jLabel9.setText("Registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 2, 15, 2);
        pnlBtnNuevo.add(jLabel9, gridBagConstraints);

        bkAulas.add(pnlBtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 169, -1, -1));

        pnlBtnBorrar.setBackground(new java.awt.Color(239, 239, 239));
        pnlBtnBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        pnlBtnBorrar.setMaximumSize(new java.awt.Dimension(100, 100));
        pnlBtnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnBorrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnBorrarMouseExited(evt);
            }
        });
        pnlBtnBorrar.setLayout(new java.awt.GridBagLayout());

        icoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Erase_36px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 32, 0, 32);
        pnlBtnBorrar.add(icoB, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 127, 80));
        jLabel11.setText("Borrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        pnlBtnBorrar.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 127, 80));
        jLabel12.setText("Registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 2, 14, 2);
        pnlBtnBorrar.add(jLabel12, gridBagConstraints);

        bkAulas.add(pnlBtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 293, -1, -1));

        pnlBtnActualizar.setBackground(new java.awt.Color(239, 239, 239));
        pnlBtnActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        pnlBtnActualizar.setMaximumSize(new java.awt.Dimension(100, 100));
        pnlBtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnActualizarMouseExited(evt);
            }
        });
        pnlBtnActualizar.setLayout(new java.awt.GridBagLayout());

        icoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Edit File_36px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 32, 0, 32);
        pnlBtnActualizar.add(icoA, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(154, 205, 50));
        jLabel5.setText("Actualizar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(8, 2, 0, 2);
        pnlBtnActualizar.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(154, 205, 50));
        jLabel6.setText("Registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 2, 13, 2);
        pnlBtnActualizar.add(jLabel6, gridBagConstraints);

        bkAulas.add(pnlBtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 413, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bkAulas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 185, 715, 390));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back To_35px.png"))); // NOI18N
        btnRegresar.setMaximumSize(new java.awt.Dimension(40, 37));
        btnRegresar.setMinimumSize(new java.awt.Dimension(40, 37));
        btnRegresar.setPreferredSize(new java.awt.Dimension(40, 37));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        bkAulas.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkAulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkAulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnMenuItemStateChanged
        if(btnMenu.isSelected()){
            panelOPC.setVisible(true);
        }else{
            panelOPC.setVisible(false);
        }
    }//GEN-LAST:event_btnMenuItemStateChanged

    private void pnlBtnNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnNuevoMouseEntered
        pnlBtnNuevo.setBackground(new Color(0,191,255));
        icoN.setIcon(addW);
    }//GEN-LAST:event_pnlBtnNuevoMouseEntered

    private void pnlBtnNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnNuevoMouseExited
        pnlBtnNuevo.setBackground(new Color(240,240,240));
        icoN.setIcon(add);
    }//GEN-LAST:event_pnlBtnNuevoMouseExited

    private void pnlBtnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnNuevoMouseClicked
        pnlBtnNuevo.setBackground(new Color(240,240,240));
        icoN.setIcon(add);
        dlgNuevo.setLocationRelativeTo(this);
        dlgNuevo.setVisible(true);
    }//GEN-LAST:event_pnlBtnNuevoMouseClicked

    private void pnlBtnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnBorrarMouseClicked
        pnlBtnBorrar.setBackground(new Color(240,240,240));
        icoB.setIcon(ers);
        try {
            agregarAulaCombo();
        } catch (SQLException ex) {
            Logger.getLogger(Aula.class.getName()).log(Level.SEVERE, null, ex);
        }
        dlgBorrar.setLocationRelativeTo(this);
        dlgBorrar.setVisible(true);
    }//GEN-LAST:event_pnlBtnBorrarMouseClicked

    private void pnlBtnBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnBorrarMouseEntered
        pnlBtnBorrar.setBackground(new Color(255,127,80));
        icoB.setIcon(ersW);
    }//GEN-LAST:event_pnlBtnBorrarMouseEntered

    private void pnlBtnBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnBorrarMouseExited
        pnlBtnBorrar.setBackground(new Color(240,240,240));
        icoB.setIcon(ers);
    }//GEN-LAST:event_pnlBtnBorrarMouseExited

    private void pnlBtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnActualizarMouseClicked
        pnlBtnActualizar.setBackground(new Color(240, 240, 240));
        icoA.setIcon(upd);
        try {
            agregarAulaCombo();
        } catch (SQLException ex) {
            Logger.getLogger(Aula.class.getName()).log(Level.SEVERE, null, ex);
        }
        dlgActualizar.setLocationRelativeTo(this);
        dlgActualizar.setVisible(true);
    }//GEN-LAST:event_pnlBtnActualizarMouseClicked

    private void pnlBtnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnActualizarMouseEntered
        pnlBtnActualizar.setBackground(new Color(154,205,50));
        icoA.setIcon(updW);
    }//GEN-LAST:event_pnlBtnActualizarMouseEntered

    private void pnlBtnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnActualizarMouseExited
        pnlBtnActualizar.setBackground(new Color(240, 240, 240));
        icoA.setIcon(upd);
    }//GEN-LAST:event_pnlBtnActualizarMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtAula.getText().trim().isEmpty()){
            try {
                AulaDB aula = new AulaDB();
                aula.setAula(txtAula.getText());
                dlgNuevo.setVisible(false);
                dlgNuevo.dispose();
                JOptionPane.showMessageDialog(null, "Los datos de han registrado");
                txtAula.setText("");
                getTable();
            } catch (SQLException ex) {
                Logger.getLogger(Aula.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor no debe los datos en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dlgNuevo.setVisible(false);
        dlgNuevo.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtAulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAulaKeyTyped
        if(txtAula.getText().length()>=25) {  
            evt.consume();
        }
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnGuardar.doClick();
        }
    }//GEN-LAST:event_txtAulaKeyTyped

    private void btnGuardarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnGuardar.doClick();
        }
    }//GEN-LAST:event_btnGuardarKeyTyped

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        dlgBorrar.setVisible(false);
        dlgBorrar.dispose();
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
//        HashMap<String, Integer> map = aula.primerCombo();
//        lblSeleccion.setText(map.get(jComboBox1.getSelectedItem().toString()).toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnEliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRegistroActionPerformed
        int opc = JOptionPane.showConfirmDialog(null, "SI HACE ESTO SE BORRARAN TODOS LOS REGISTROS QUE SE HICIERON CON ESTE AULA!!!", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
        if(opc == JOptionPane.YES_OPTION){
            try {
                HashMap<String, Integer> map = aula.primerCombo();
                //lblSeleccion.setText(map.get(jComboBox1.getSelectedItem().toString()).toString());
                int seleccion = map.get(jComboBox1.getSelectedItem().toString());
                PrestamoDB prestamo = new PrestamoDB();
                if(prestamo.getPrestamoActivo(String.valueOf(seleccion), 1)){
                    JOptionPane.showMessageDialog(null, "Los datos de han eliminado");
                    aula.destroyAula(seleccion);
                    dlgBorrar.setVisible(false);
                    dlgBorrar.dispose();
                    getTable();
                }else{
                    JOptionPane.showMessageDialog(null, "No se puede eliminar!!!\nEl aula que desea eliminar se encuentra registrada en un prestamo de Videoproyector\nprimero registre la devolucion del Videoproyector\ndespues proceda a eliminar el aula\n\nRECUERDE QUE ESTA ACCION ELIMINARA TODOS LOS REGISTROS RELACIONADOS");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Aula.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha borrado el registro\n\nRecuerde que esta accion es irreversible y si es ejecutada\nse borraran todos los registros relacionados a este aula", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarRegistroActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    try {
        HashMap<String, Integer> map = aula.primerCombo();
        //lblSeleccion.setText(map.get(jComboBox1.getSelectedItem().toString()).toString());
        int seleccion = map.get(jComboBox2.getSelectedItem().toString());
        if (!txtAulaNuevo.getText().trim().isEmpty()){
            aula.updAula(seleccion, txtAulaNuevo.getText());    //metodo actualizar
            dlgActualizar.setVisible(false);    //cerrar dialog
            dlgActualizar.dispose();            //cerrar dialog
            pnlCombo.setVisible(true);          //panel del comboBox
            pnlFormulario.setVisible(false);    //panel del formulario
            btnActualizar.setEnabled(false);    //boton actualizar
            getTable();
        }else{
            JOptionPane.showMessageDialog(null, "Error no puede dejar la casilla en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException ex) {
        Logger.getLogger(Aula.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar2ActionPerformed
        pnlCombo.setVisible(true);          //panel del comboBox
        pnlFormulario.setVisible(false);    //panel del formulario
        
        btnActualizar.setEnabled(false);    //boton actualizar
        
        dlgActualizar.setVisible(false);    //cerrar dialog
        dlgActualizar.dispose();            //cerrar dialog
    }//GEN-LAST:event_btnCerrar2ActionPerformed

    private void btnActualizarCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCombActionPerformed
        HashMap<String, Integer> map = aula.primerCombo();
        int seleccion = map.get(jComboBox2.getSelectedItem().toString());    
        
        pnlCombo.setVisible(false);
        pnlFormulario.setVisible(true);
        txtAulaNuevo.setText(aula.getAula(seleccion));
        btnActualizar.setEnabled(true);
    }//GEN-LAST:event_btnActualizarCombActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    try {
        Departamento depart = new Departamento();
        depart.setVisible(true);
        this.setVisible(false);
        this.dispose();
    } catch (SQLException ex) {
        Logger.getLogger(Aula.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    try {
        Profesor profe = new Profesor();
        profe.setVisible(true);
        this.setVisible(false);
        this.dispose();
    } catch (SQLException ex) {
        Logger.getLogger(Aula.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    try {
        Videoproyector vid = new Videoproyector();
        vid.setVisible(true);
        this.setVisible(false);
        this.dispose();
    } catch (SQLException ex) {
        Logger.getLogger(Aula.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void ico3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico3MouseClicked
        AlPrestamo pres = new AlPrestamo();
        pres.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico3MouseClicked

    private void ico4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico4MouseClicked
        ADevolucion dev = new ADevolucion();
        dev.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico4MouseClicked

    private void ico5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico5MouseClicked
        ARegistro reg = new ARegistro();
        reg.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico5MouseClicked

    private void txtAulaNuevoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAulaNuevoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnActualizar.doClick();
        }
    }//GEN-LAST:event_txtAulaNuevoKeyTyped

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Articulo art = new Articulo();
        art.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Aula().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Aula.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
AulaDB aula = new AulaDB();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aulas;
    private javax.swing.JPanel barraSeparadora1;
    private javax.swing.JPanel bkAulas;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarComb;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnCerrar2;
    private javax.swing.JButton btnEliminarRegistro;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JToggleButton btnMenu;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JDialog dlgActualizar;
    private javax.swing.JDialog dlgBorrar;
    private javax.swing.JDialog dlgNuevo;
    private javax.swing.JLabel ico1;
    private javax.swing.JLabel ico2;
    private javax.swing.JLabel ico3;
    private javax.swing.JLabel ico4;
    private javax.swing.JLabel ico5;
    private javax.swing.JLabel icoA;
    private javax.swing.JLabel icoB;
    private javax.swing.JLabel icoN;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLydPane1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel lblAulaNom;
    private javax.swing.JLabel lblAulaNom1;
    private javax.swing.JLabel lblCabecera1;
    private javax.swing.JLabel lblCabecera2;
    private javax.swing.JLabel lblCabecera3;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JPanel panelOPC;
    private javax.swing.JPanel pnlBkActualizar;
    private javax.swing.JPanel pnlBkBorrar;
    private javax.swing.JPanel pnlBkNuevo;
    private javax.swing.JPanel pnlBtnActualizar;
    private javax.swing.JPanel pnlBtnBorrar;
    private javax.swing.JPanel pnlBtnNuevo;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlCombo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlFormularioCrear;
    private javax.swing.JTextField txtAula;
    private javax.swing.JTextField txtAulaNuevo;
    // End of variables declaration//GEN-END:variables
}
