/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyector;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import org.mindrot.jbcrypt.BCrypt;
import proyector.dataBase.crud.DepartamentoDB;
import proyector.dataBase.crud.PrestamoDB;
import proyector.dataBase.crud.UsuarioReadDB;

/**
 *
 * @author JuanGSot
 */
public class Departamento extends javax.swing.JFrame {
String date = new SimpleDateFormat("dd-MM-yyyy").format(new Date());
ImageIcon img = new ImageIcon("./src/imagenes/logo-adm.png");
ImageIcon addW = new ImageIcon("./src/imagenes/Add New_36pxW.png");
ImageIcon add = new ImageIcon("./src/imagenes/Add New_36px.png");
private static Boolean valido = false;
    /**
     * Creates new form Departamento
     * @throws java.sql.SQLException
     */
    public Departamento() throws SQLException{
        initComponents();
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);     //indica la velocidad de movimiento del scroll
        dibujarDepartamentos();                                     //dibuja cada departamento en un jPanel
        panelOPC.setVisible(false);                                 //menu de navegacion
        lblHide.setVisible(false);                                  //id de cada departamento en un jpanel 
        
        txtNom.setTransferHandler(null);
        txtAbrv.setTransferHandler(null);
        txtEnc.setTransferHandler(null);
        
        txtNom1.setTransferHandler(null);
        txtAbrv1.setTransferHandler(null);
        txtEnc1.setTransferHandler(null);
        
        labelFecha.setText(date);                                   //coloca la fecha
        Timer timer = new Timer(500, (ActionEvent e) -> {
            reloj();                                                //coloca la hora
        });
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.setInitialDelay(0);
        timer.start();
    }

    /**
     * Se encarga de colocar la hora con un formato especifico
     */
    public void reloj(){
        labelHora.setText(new SimpleDateFormat("hh:mm:ss a").format(new Date()));
    }
    
    /**
     * llama al metodo miPanel e ingresa cada departamento dentro de este
     * cada panel es agregado a un panel contenedor 
     * este metodo calcula la altura que debe tener de acuerdo a la cantidad de datos
     * @throws SQLException 
     */
    public void dibujarDepartamentos() throws SQLException{
        DepartamentoDB depart = new DepartamentoDB();
        String[][] datos;
        datos = depart.getDepartamentos();
        
        for (int i = 0; i < datos.length; i++) {
            miPanel(datos, i);
        }
        //acomodar componentes
        int filas = (pnlContenedor.getComponentCount() / 4);
        int altura = (325 * (filas + 1)); //la altura es la cantidad de filas + el espaciado
        pnlContenedor.setPreferredSize(new Dimension(778, altura));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dlgNuevo = new javax.swing.JDialog();
        pnlBkNuevo = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblNom = new javax.swing.JLabel();
        lblAbb = new javax.swing.JLabel();
        lblEnc = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtAbrv = new javax.swing.JTextField();
        txtEnc = new javax.swing.JTextField();
        barraSeparadora = new javax.swing.JPanel();
        barraSeparadora1 = new javax.swing.JPanel();
        barraSeparadora2 = new javax.swing.JPanel();
        dlgEditar = new javax.swing.JDialog();
        pnlBkEditar = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblAbbrev = new javax.swing.JLabel();
        lblEncarg = new javax.swing.JLabel();
        txtNom1 = new javax.swing.JTextField();
        txtAbrv1 = new javax.swing.JTextField();
        txtEnc1 = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCerrar1 = new javax.swing.JButton();
        lblHide = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        dlgConfirm = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btnComprobar = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        bkDepartamentos = new javax.swing.JPanel();
        pnlCabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        panelOPC = new javax.swing.JPanel();
        ico3 = new javax.swing.JLabel();
        ico4 = new javax.swing.JLabel();
        ico5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        departamentos = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        pnlContenedor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ico1 = new javax.swing.JLabel();
        lblBtn1 = new javax.swing.JLabel();
        lblBtn2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        dlgNuevo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dlgNuevo.setMinimumSize(new java.awt.Dimension(630, 345));
        dlgNuevo.setModal(true);
        dlgNuevo.setUndecorated(true);
        dlgNuevo.setResizable(false);

        pnlBkNuevo.setBackground(new java.awt.Color(255, 255, 255));
        pnlBkNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        pnlBkNuevo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        pnlBkNuevo.setMinimumSize(new java.awt.Dimension(630, 345));
        pnlBkNuevo.setPreferredSize(new java.awt.Dimension(630, 345));

        lbltitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbltitulo.setText("Nuevo Departamento");

        jPanel3.setBackground(new java.awt.Color(1, 200, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(12, 193, 243));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnGuardar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_22px.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblNom.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNom.setText("Nombre");

        lblAbb.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAbb.setText("Abreviatura");

        lblEnc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblEnc.setText("Encargado");

        txtNom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNom.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        txtNom.setMinimumSize(new java.awt.Dimension(190, 30));
        txtNom.setPreferredSize(new java.awt.Dimension(190, 30));
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomKeyTyped(evt);
            }
        });

        txtAbrv.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtAbrv.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        txtAbrv.setMinimumSize(new java.awt.Dimension(190, 30));
        txtAbrv.setPreferredSize(new java.awt.Dimension(190, 30));
        txtAbrv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAbrvKeyTyped(evt);
            }
        });

        txtEnc.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtEnc.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        txtEnc.setMinimumSize(new java.awt.Dimension(190, 30));
        txtEnc.setPreferredSize(new java.awt.Dimension(190, 30));
        txtEnc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEncKeyTyped(evt);
            }
        });

        barraSeparadora.setBackground(new java.awt.Color(0, 0, 0));
        barraSeparadora.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout barraSeparadoraLayout = new javax.swing.GroupLayout(barraSeparadora);
        barraSeparadora.setLayout(barraSeparadoraLayout);
        barraSeparadoraLayout.setHorizontalGroup(
            barraSeparadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadoraLayout.setVerticalGroup(
            barraSeparadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        barraSeparadora1.setBackground(new java.awt.Color(0, 0, 0));
        barraSeparadora1.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout barraSeparadora1Layout = new javax.swing.GroupLayout(barraSeparadora1);
        barraSeparadora1.setLayout(barraSeparadora1Layout);
        barraSeparadora1Layout.setHorizontalGroup(
            barraSeparadora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadora1Layout.setVerticalGroup(
            barraSeparadora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        barraSeparadora2.setBackground(new java.awt.Color(0, 0, 0));
        barraSeparadora2.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout barraSeparadora2Layout = new javax.swing.GroupLayout(barraSeparadora2);
        barraSeparadora2.setLayout(barraSeparadora2Layout);
        barraSeparadora2Layout.setHorizontalGroup(
            barraSeparadora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadora2Layout.setVerticalGroup(
            barraSeparadora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBkNuevoLayout = new javax.swing.GroupLayout(pnlBkNuevo);
        pnlBkNuevo.setLayout(pnlBkNuevoLayout);
        pnlBkNuevoLayout.setHorizontalGroup(
            pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lbltitulo))
                    .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(98, 98, 98)
                                .addComponent(btnCerrar))
                            .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBkNuevoLayout.createSequentialGroup()
                                    .addComponent(lblEnc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                                    .addComponent(lblAbb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAbrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                                    .addComponent(lblNom)
                                    .addGap(65, 65, 65)
                                    .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(barraSeparadora, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(barraSeparadora1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(barraSeparadora2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))))))
                .addGap(16, 16, 16))
        );
        pnlBkNuevoLayout.setVerticalGroup(
            pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBkNuevoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbltitulo)
                .addGap(36, 36, 36)
                .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNom))
                .addGap(0, 0, 0)
                .addComponent(barraSeparadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAbrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAbb))
                .addGap(0, 0, 0)
                .addComponent(barraSeparadora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnc))
                .addGap(0, 0, 0)
                .addComponent(barraSeparadora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlBkNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCerrar))
                .addGap(30, 30, 30))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dlgNuevoLayout = new javax.swing.GroupLayout(dlgNuevo.getContentPane());
        dlgNuevo.getContentPane().setLayout(dlgNuevoLayout);
        dlgNuevoLayout.setHorizontalGroup(
            dlgNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgNuevoLayout.setVerticalGroup(
            dlgNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgNuevo.getAccessibleContext().setAccessibleParent(this);

        dlgEditar.setMinimumSize(new java.awt.Dimension(672, 330));
        dlgEditar.setModal(true);
        dlgEditar.setUndecorated(true);
        dlgEditar.setResizable(false);

        pnlBkEditar.setBackground(new java.awt.Color(0, 191, 255));
        pnlBkEditar.setMinimumSize(new java.awt.Dimension(672, 330));
        pnlBkEditar.setPreferredSize(new java.awt.Dimension(672, 330));

        jPanel6.setBackground(new java.awt.Color(253, 184, 19));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(154, 205, 50));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Actualizar Departamento");

        lblNombre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        lblAbbrev.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAbbrev.setForeground(new java.awt.Color(255, 255, 255));
        lblAbbrev.setText("Abreviatura");

        lblEncarg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblEncarg.setForeground(new java.awt.Color(255, 255, 255));
        lblEncarg.setText("Encargado");

        txtNom1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNom1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));
        txtNom1.setMinimumSize(new java.awt.Dimension(200, 30));
        txtNom1.setPreferredSize(new java.awt.Dimension(200, 30));
        txtNom1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNom1KeyTyped(evt);
            }
        });

        txtAbrv1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtAbrv1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));
        txtAbrv1.setMinimumSize(new java.awt.Dimension(200, 30));
        txtAbrv1.setPreferredSize(new java.awt.Dimension(200, 30));
        txtAbrv1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAbrv1KeyTyped(evt);
            }
        });

        txtEnc1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtEnc1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));
        txtEnc1.setMinimumSize(new java.awt.Dimension(200, 30));
        txtEnc1.setPreferredSize(new java.awt.Dimension(200, 30));
        txtEnc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEnc1KeyTyped(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pencil_22px.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCerrar1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCerrar1.setText("Cerrar");
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(1, 200, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBkEditarLayout = new javax.swing.GroupLayout(pnlBkEditar);
        pnlBkEditar.setLayout(pnlBkEditarLayout);
        pnlBkEditarLayout.setHorizontalGroup(
            pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBkEditarLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBkEditarLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblTitulo))
                    .addGroup(pnlBkEditarLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnActualizar)
                            .addGroup(pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombre)
                                .addComponent(lblAbbrev)
                                .addComponent(lblEncarg)))
                        .addGroup(pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBkEditarLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEnc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAbrv1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlBkEditarLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(btnCerrar1)
                                .addGap(56, 56, 56)
                                .addComponent(lblHide)))))
                .addGap(568, 568, 568))
        );
        pnlBkEditarLayout.setVerticalGroup(
            pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBkEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(48, 48, 48)
                .addGroup(pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAbbrev)
                    .addComponent(txtAbrv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncarg)
                    .addComponent(txtEnc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlBkEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCerrar1)
                    .addComponent(lblHide))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblAbbrev.getAccessibleContext().setAccessibleName("lblAbbrv");
        lblEncarg.getAccessibleContext().setAccessibleName("lblEnc");
        btnCerrar1.getAccessibleContext().setAccessibleName("btnCerrar");

        javax.swing.GroupLayout dlgEditarLayout = new javax.swing.GroupLayout(dlgEditar.getContentPane());
        dlgEditar.getContentPane().setLayout(dlgEditarLayout);
        dlgEditarLayout.setHorizontalGroup(
            dlgEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgEditarLayout.setVerticalGroup(
            dlgEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBkEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgEditar.getAccessibleContext().setAccessibleParent(this);

        dlgConfirm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgConfirm.setTitle("[Confirmar Acción]");
        dlgConfirm.setMinimumSize(new java.awt.Dimension(400, 300));
        dlgConfirm.setModal(true);

        jPanel9.setBackground(new java.awt.Color(255, 183, 77));

        jLabel40.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("<html>Esta acción necesita su<br><b>Usuario</b> y <b>Contraseña</b></html>");

        jLabel41.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Usuario:");

        jLabel42.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Contraseña:");

        btnComprobar.setText("Validar Acción");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/niceGuy-60.png"))); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtUsuario.setMinimumSize(new java.awt.Dimension(111, 30));
        txtUsuario.setPreferredSize(new java.awt.Dimension(111, 30));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtPass.setMinimumSize(new java.awt.Dimension(111, 30));
        txtPass.setPreferredSize(new java.awt.Dimension(111, 30));
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel43)
                .addGap(18, 18, 18))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnComprobar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnComprobar)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout dlgConfirmLayout = new javax.swing.GroupLayout(dlgConfirm.getContentPane());
        dlgConfirm.getContentPane().setLayout(dlgConfirmLayout);
        dlgConfirmLayout.setHorizontalGroup(
            dlgConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgConfirmLayout.setVerticalGroup(
            dlgConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Departamentos]");
        setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        setIconImage(img.getImage());
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setResizable(false);

        bkDepartamentos.setBackground(new java.awt.Color(255, 255, 255));
        bkDepartamentos.setMinimumSize(new java.awt.Dimension(1024, 600));
        bkDepartamentos.setPreferredSize(new java.awt.Dimension(1024, 600));
        bkDepartamentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecera.setBackground(new java.awt.Color(1, 200, 1));
        pnlCabecera.setMinimumSize(new java.awt.Dimension(1024, 83));
        pnlCabecera.setPreferredSize(new java.awt.Dimension(1024, 83));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tecnm2.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sep.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hora");

        labelHora.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 255, 255));
        labelHora.setText("00:00:00 PM");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha");

        labelFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("00-00-0000");

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(labelHora)
                .addGap(107, 107, 107)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(labelFecha)
                .addGap(36, 36, 36)
                .addComponent(jLabel2))
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelHora)
                            .addComponent(jLabel5)
                            .addComponent(labelFecha)))
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bkDepartamentos.add(pnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Checklist_24px.png"))); // NOI18N
        jToggleButton1.setFocusPainted(false);
        jToggleButton1.setMaximumSize(new java.awt.Dimension(40, 37));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(40, 37));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(40, 37));
        jToggleButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        bkDepartamentos.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        panelOPC.setBackground(new java.awt.Color(250, 250, 250));
        panelOPC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 173, 179), 1, true));
        panelOPC.setLayout(new java.awt.GridBagLayout());

        ico3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo_32px.png"))); // NOI18N
        ico3.setToolTipText("Prestamo");
        ico3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        panelOPC.add(ico3, gridBagConstraints);

        ico4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/devolu_32px.png"))); // NOI18N
        ico4.setToolTipText("Devolución");
        ico4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico4, gridBagConstraints);

        ico5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registr_32px.png"))); // NOI18N
        ico5.setToolTipText("Registros");
        ico5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(ico5, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prof_42px.png"))); // NOI18N
        jLabel7.setToolTipText("Profesores");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
        panelOPC.add(jLabel7, gridBagConstraints);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aul_42px.png"))); // NOI18N
        jLabel8.setToolTipText("Aulas");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(jLabel8, gridBagConstraints);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Video Projector_42px.png"))); // NOI18N
        jLabel9.setToolTipText("Videoproyectores");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelOPC.add(jLabel9, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Electrical_42px.png"))); // NOI18N
        jLabel4.setToolTipText("Artículos");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 0);
        panelOPC.add(jLabel4, gridBagConstraints);

        bkDepartamentos.add(panelOPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, -1, -1));

        departamentos.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        departamentos.setText("Departamentos");
        bkDepartamentos.add(departamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 109, -1, -1));

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 6, 15));
        scrollPane.setViewportView(pnlContenedor);

        bkDepartamentos.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 900, 410));

        jPanel2.setBackground(new java.awt.Color(239, 239, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new java.awt.GridBagLayout());

        ico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add New_36px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        jPanel2.add(ico1, gridBagConstraints);

        lblBtn1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblBtn1.setForeground(new java.awt.Color(0, 191, 255));
        lblBtn1.setText("Nuevo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(lblBtn1, gridBagConstraints);

        lblBtn2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblBtn2.setForeground(new java.awt.Color(0, 191, 255));
        lblBtn2.setText("Registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 5, 9);
        jPanel2.add(lblBtn2, gridBagConstraints);

        bkDepartamentos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 70, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back To_35px.png"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(40, 37));
        jButton1.setMinimumSize(new java.awt.Dimension(40, 37));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 37));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bkDepartamentos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        dlgNuevo.setLocationRelativeTo(this);
        dlgNuevo.setVisible(true); 
        jPanel2.setBackground(new Color(239,239,239));
        ico1.setIcon(add);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dlgNuevo.setVisible(false);
        dlgNuevo.dispose();
        
        txtNom.setText("");
        txtAbrv.setText("");
        txtEnc.setText("");
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyTyped
        if(txtNom.getText().length()>=40) {  
            evt.consume();
        }
        char c = evt.getKeyChar(); //probar introducir solo caracteres
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnGuardar.doClick();
        }
    }//GEN-LAST:event_txtNomKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
        if(!txtNom.getText().trim().isEmpty() &&  !txtAbrv.getText().trim().isEmpty() && !txtEnc.getText().trim().isEmpty()){
            String datos[] = { txtNom.getText(), txtAbrv.getText(), txtEnc.getText() };
            DepartamentoDB dept = new DepartamentoDB();
            dept.setDepartamento(datos);
            //redibujar paneles
            pnlContenedor.removeAll();
            pnlContenedor.repaint();
            dibujarDepartamentos();
            //cierra dialog
            dlgNuevo.setVisible(false);
            dlgNuevo.dispose();
            
            JOptionPane.showMessageDialog(null, "Se ha creado el nuevo departamento exitosamente.");
        }else{
            JOptionPane.showMessageDialog(null, "Error!!!\n No puede dejar ningun campo en blanco.");
        }
        //limpia casillas
        txtNom.setText("");
        txtAbrv.setText("");
        txtEnc.setText("");
    } catch (SQLException ex) {
        Logger.getLogger(Departamento.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtAbrvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbrvKeyTyped
        if(txtAbrv.getText().length()>=15) {  
            evt.consume();
        }
        char c = evt.getKeyChar(); //probar introducir solo caracteres
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnGuardar.doClick();
        }
    }//GEN-LAST:event_txtAbrvKeyTyped

    private void txtEncKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEncKeyTyped
        if(txtEnc.getText().length()>=50) {
            evt.consume();
        }
        char c = evt.getKeyChar(); //probar introducir solo caracteres
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnGuardar.doClick();
        }
    }//GEN-LAST:event_txtEncKeyTyped

    private void jToggleButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton1ItemStateChanged
        if(jToggleButton1.isSelected()){
            panelOPC.setVisible(true);
        }else{
            panelOPC.setVisible(false);
        }
    }//GEN-LAST:event_jToggleButton1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        jPanel2.setBackground(new Color(0,191,255));
        ico1.setIcon(addW);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        jPanel2.setBackground(new Color(239,239,239));
        ico1.setIcon(add);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    try {
        Aula aula = new Aula();
        aula.setVisible(true);
        this.setVisible(false);
        this.dispose();
    } catch (SQLException ex) {
        Logger.getLogger(Departamento.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(!txtNom1.getText().trim().isEmpty() && !txtAbrv1.getText().trim().isEmpty() && !txtEnc1.getText().trim().isEmpty()){
            try {
                String[] actualizar = {txtNom1.getText(), txtAbrv1.getText(), txtEnc1.getText()};
                DepartamentoDB depart = new DepartamentoDB();
                depart.updDepartamento(Integer.parseInt(lblHide.getText()), actualizar);
                
                //redibujar paneles
                pnlContenedor.removeAll();
                pnlContenedor.repaint();
                dibujarDepartamentos();
                //dialog cerrar
                dlgEditar.setVisible(false);
                dlgEditar.dispose();
                //limpiar casillas
                txtNom1.setText("");
                txtAbrv1.setText("");
                txtEnc1.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Departamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error!!!\n No puede dejar ningun campo en blanco.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtNom1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNom1KeyTyped
        if(txtNom1.getText().length()>=40) {
            evt.consume();
        }
        char c = evt.getKeyChar(); //probar introducir solo caracteres
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnActualizar.doClick();
        }
    }//GEN-LAST:event_txtNom1KeyTyped

    private void txtAbrv1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbrv1KeyTyped
        if(txtAbrv1.getText().length()>=15) {
            evt.consume();
        }
        char c = evt.getKeyChar(); //probar introducir solo caracteres
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnActualizar.doClick();
        }
    }//GEN-LAST:event_txtAbrv1KeyTyped

    private void txtEnc1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnc1KeyTyped
        if(txtEnc1.getText().length()>=40) {
            evt.consume();
        }
        char c = evt.getKeyChar(); //probar introducir solo caracteres
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            btnActualizar.doClick();
        }
    }//GEN-LAST:event_txtEnc1KeyTyped

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        dlgEditar.setVisible(false);
        dlgEditar.dispose();
        //limpiar casillas
        txtNom1.setText("");
        txtAbrv1.setText("");
        txtEnc1.setText("");
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
    try {
        Profesor profe = new Profesor();
        profe.setVisible(true);
        this.setVisible(false);
        this.dispose();
    } catch (SQLException ex) {
        Logger.getLogger(Departamento.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
    try {
        Videoproyector vid = new Videoproyector();
        vid.setVisible(true);
        this.setVisible(false);
        this.dispose();
    } catch (SQLException ex) {
        Logger.getLogger(Departamento.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void ico3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico3MouseClicked
        AlPrestamo pres = new AlPrestamo();
        pres.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico3MouseClicked

    private void ico4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico4MouseClicked
        ADevolucion dev = new ADevolucion();
        dev.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico4MouseClicked

    private void ico5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico5MouseClicked
        ARegistro reg = new ARegistro();
        reg.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ico5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Articulo art = new Articulo();
        art.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        String crdncial = txtUsuario.getText().trim();
        try {
            UsuarioReadDB leer = new UsuarioReadDB();
            if (leer.getExisteUsuario(crdncial)) {
                String hashed = leer.getPass(crdncial);
                if (BCrypt.checkpw(String.valueOf(txtPass.getPassword()), hashed)) {
                    if(leer.getEsAdminUsuario(crdncial)){
                        valido = true;
                        txtUsuario.setText("");
                        txtPass.setText("");
                        dlgConfirm.setVisible(false);
                        dlgConfirm.dispose();
                    }else{
                        throw new Exception();
                    }
                }else{
                    throw new Exception();
                }
            }else{
                throw new Exception();
            }
        }catch(SQLException ex){
            System.out.println("Error al comprobar usuario:" + ex);
        }catch(Exception e){
            txtUsuario.setText("");
            txtPass.setText("");
            valido = false;
            JOptionPane.showMessageDialog(null,"Compruebe los datos ingresados, es posible que:\n-Su usuario no sea administrador\n-No ingreso sus datos correctamente");
        }
    }//GEN-LAST:event_btnComprobarActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        if (txtUsuario.getText().length() >= 15) {
            evt.consume();
        }
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            btnComprobar.doClick();
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        if (txtPass.getPassword().length >= 12) {
            evt.consume();
        }
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            btnComprobar.doClick();
        }
    }//GEN-LAST:event_txtPassKeyTyped
   
    /**
     * Metodo encargado de crear un jPanel con una estructura predefinida para recibir 
     * cada departamento
     * @param datos
     * @param i 
     */
    public final void miPanel(String[][] datos, int i){
        //int y = Integer.parseInt(str);
        ImageIcon imgU = new ImageIcon("./src/imagenes/User_36px.png");
        ImageIcon img1 = new ImageIcon("./src/imagenes/trash-24.png");
        ImageIcon img2 = new ImageIcon("./src/imagenes/pencil-24.png");
        JPanel anon = new JPanel();
            anon.setPreferredSize(new Dimension(210, 305));//190, 290 o era 195, 290
            anon.setBackground(new Color(26, 200, 160));
            
            anon.setBorder(new LineBorder(new Color(173, 173, 173), 2, true));
            anon.setLayout(new GridBagLayout());
            GridBagConstraints c = new GridBagConstraints();
            c.anchor = GridBagConstraints.CENTER;
            c.gridx = 0;
            c.fill = GridBagConstraints.CENTER;
            c.insets = new Insets(5,0,10,0);

            JLabel lbico1 = new JLabel();
            lbico1.setIcon(imgU);
            c.gridy = 0;
            anon.add(lbico1, c);

            JLabel lb1 = new JLabel("Departamento:");
            lb1.setForeground(Color.white);
            lb1.setFont(new Font("SansSerif", Font.BOLD,13));
            c.gridy = 1;
            anon.add(lb1, c);

            JLabel lb1R = new JLabel("<html>"+datos[i][0]+"</html>");
            lb1R.setForeground(Color.white);
            lb1R.setFont(new Font("SansSerif", Font.PLAIN,12));
            c.gridy = 2;
            anon.add(lb1R, c);

            JLabel lb2 = new JLabel("Abreviatura:");
            lb2.setForeground(Color.white);
            lb2.setFont(new Font("SansSerif", Font.BOLD,13));
            c.gridy = 3;
            anon.add(lb2, c);

            JLabel lb2R = new JLabel(datos[i][1]);
            lb2R.setForeground(Color.white);
            lb2R.setFont(new Font("SansSerif", Font.PLAIN,12));
            c.gridy = 4;
            anon.add(lb2R, c);

            JLabel lb3 = new JLabel("Encargado(a):");
            lb3.setForeground(Color.white);
            lb3.setFont(new Font("SansSerif", Font.BOLD,13));
            c.gridy = 5;
            anon.add(lb3, c);

            JLabel lb3R = new JLabel(datos[i][2]);
            lb3R.setForeground(Color.white);
            lb3R.setFont(new Font("SansSerif", Font.PLAIN,9));
            c.gridy = 6;
            anon.add(lb3R, c);
            
            JPanel pnl1 = new JPanel(); //pequeño panel que contiene los botones
            pnl1.setPreferredSize(new Dimension(180, 25));
            pnl1.setOpaque(false);
            pnl1.setBorder(new EmptyBorder(0,0,0,0));
            c.gridy = 7;
            pnl1.setLayout(new GridLayout(1,2));

            JLabel btnDelDep1 = new JLabel("Eliminar", SwingConstants.CENTER);
            btnDelDep1.setIcon(img1);
            btnDelDep1.setForeground(new Color(253, 216, 53));
            btnDelDep1.setFont(new Font("SansSerif", Font.BOLD,11));
            pnl1.add(btnDelDep1);
            
            JLabel btnEditDep1 = new JLabel("Editar", SwingConstants.CENTER);
            btnEditDep1.setIcon(img2);
            btnEditDep1.setForeground(new Color(255, 255, 255));
            btnEditDep1.setFont(new Font("SansSerif", Font.BOLD,11));
            pnl1.add(btnEditDep1);
            
            btnDelDep1.addMouseListener(new MouseAdapter(){
                @Override
                public void mouseExited(MouseEvent e){
                    btnDelDep1.setOpaque(false);
                    btnDelDep1.setBackground(new Color(60,72,84));
                }
                @Override
                public void mouseEntered(MouseEvent e){
                    btnDelDep1.setOpaque(true);
                    btnDelDep1.setBackground(new Color(255, 85, 85));
                }

                @Override
                public void mouseClicked(MouseEvent e) {
                dlgConfirm.setLocationRelativeTo(bkDepartamentos);
                dlgConfirm.setVisible(true);

                if(valido){
                    valido = false;
                    int respuesta = JOptionPane.showConfirmDialog(null, "Desea eliminar el departamento???: " + datos[i][0] + "\n\nSI HACE ESTO SE BORRARAN TODOS LOS REGISTROS RELACIONADOS \n->ELIMINARA TODOS LOS PROFESORES \n-> TODOS LOS PRESTAMOS CON RELACION A LOS PROFESORES\n\nRECUERDE ESTA ACCION ES IRREVERSIBLE", "Eliminar registro", JOptionPane.YES_NO_OPTION);
                    if (respuesta == JOptionPane.YES_OPTION){
                       try {
                           DepartamentoDB depart = new DepartamentoDB();
                           PrestamoDB prestamo = new PrestamoDB();
                           if(prestamo.getPrestamoActivo(datos[i][3], 4)){
                            depart.destroyDepartamento(Integer.parseInt(datos[i][3]));
                            JOptionPane.showMessageDialog(null, "Se ha eliminado el departamento");
                            pnlContenedor.removeAll();
                            pnlContenedor.repaint();
                            dibujarDepartamentos();
                           }else{
                               JOptionPane.showMessageDialog(null, "No se puede eliminar!!!\n"
                                                                 + "El departamento que desea eliminar cuenta con un profesor que ha solicitado un prestamo\n"
                                                                 + "primero registre la devolucion del Videoproyector\n"
                                                                 + "despues proceda a eliminar\n\n"
                                                                 + "RECUERDE QUE ESTA ACCION ELIMINARA TODOS LOS REGISTROS RELACIONADOS");
                           }
                       } catch (SQLException ex) {
                           Logger.getLogger(Departamento.class.getName()).log(Level.SEVERE, null, ex);
                       }
                    }else{
                        JOptionPane.showMessageDialog(null, "No se ha borrado el registro\n\nRecuerde que esta accion es irreversible y si es ejecutada\nse borraran todos los registros relacionados a este departamento", "Información", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                }
            });
        
            btnEditDep1.addMouseListener(new MouseAdapter(){
                @Override
                public void mouseExited(MouseEvent e){
                    btnEditDep1.setOpaque(false);
                    btnEditDep1.setBackground(new Color(60,72,84));
                }
                @Override
                public void mouseEntered(MouseEvent e){
                    btnEditDep1.setOpaque(true);
                    btnEditDep1.setBackground(new Color(255,255,255 ));
                }
                @Override
                public void mouseClicked(MouseEvent e){
                    int respuesta = JOptionPane.showConfirmDialog(null, "Editar el departamento:" + datos[i][0], "Edición", JOptionPane.YES_NO_OPTION);
                    if (respuesta == JOptionPane.YES_OPTION){
                        try {
                            DepartamentoDB depart = new DepartamentoDB();
                            String[] dato = depart.getDepartamento(Integer.parseInt(datos[i][3]));
                            lblHide.setText(datos[i][3]);
                            txtNom1.setText(dato[0]);
                            txtAbrv1.setText(dato[1]);
                            txtEnc1.setText(dato[2]);
                            
                            dlgEditar.setLocationRelativeTo(bkDepartamentos);
                            dlgEditar.setVisible(true);
                            //JOptionPane.showMessageDialog(pnl1, "Se va a editar algun dia");
                        } catch (SQLException ex) {
                            Logger.getLogger(Departamento.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            });
            anon.add(pnl1,c);
            //anon.add(new JLabel(datos[i][3]), c.gridy =8);
            anon.revalidate();
            
        pnlContenedor.add(anon); //añade todo el jpanel al panel principal este jPanel5 se encuentra dentro del jScrolPane
        pnlContenedor.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Departamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Departamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Departamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Departamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Departamento().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Departamento.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSeparadora;
    private javax.swing.JPanel barraSeparadora1;
    private javax.swing.JPanel barraSeparadora2;
    private javax.swing.JPanel bkDepartamentos;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnComprobar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel departamentos;
    private javax.swing.JDialog dlgConfirm;
    private javax.swing.JDialog dlgEditar;
    private javax.swing.JDialog dlgNuevo;
    private javax.swing.JLabel ico1;
    private javax.swing.JLabel ico3;
    private javax.swing.JLabel ico4;
    private javax.swing.JLabel ico5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel lblAbb;
    private javax.swing.JLabel lblAbbrev;
    private javax.swing.JLabel lblBtn1;
    private javax.swing.JLabel lblBtn2;
    private javax.swing.JLabel lblEnc;
    private javax.swing.JLabel lblEncarg;
    private javax.swing.JLabel lblHide;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel panelOPC;
    private javax.swing.JPanel pnlBkEditar;
    private javax.swing.JPanel pnlBkNuevo;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txtAbrv;
    private javax.swing.JTextField txtAbrv1;
    private javax.swing.JTextField txtEnc;
    private javax.swing.JTextField txtEnc1;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNom1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
