/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyector;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ToolTipManager;
import org.mindrot.jbcrypt.BCrypt;
import proyector.dataBase.Conexion;
import proyector.dataBase.crud.CrearInicio;
import proyector.dataBase.crud.LeerInicio;
import proyector.reportes.GenerarReportes;

/**
 *
 * @author JuanGSot
 */
public final class Inicio extends javax.swing.JFrame {

    ImageIcon img = new ImageIcon(("./src/imagenes/logo-adm.png").replace('/', File.separatorChar));
    ImageIcon homeB = new ImageIcon(("./src/imagenes/HomeB24px.png").replace('/', File.separatorChar));
    ImageIcon homeW = new ImageIcon(("./src/imagenes/Home24px.png").replace('/', File.separatorChar));

    /**
     * Creates new form Inicio
     * @throws java.sql.SQLException
     */
    public Inicio() throws SQLException {
        Conexion conn = new Conexion();                                         //pruebo a conectar o crear la base de datos
        conn.getConexion();

        initComponents();
        lanzarRegistro();
        dialogAcceso.setVisible(false);

        ToolTipManager.sharedInstance().setInitialDelay(0);
        txtNom.setTransferHandler(null);
        txtAPat.setTransferHandler(null);
        txtAMat.setTransferHandler(null);
        
        //bloquear ctrl c ctrl v
        txtUsuario.setTransferHandler(null);
        
        txtNom.setTransferHandler(null);
        txtAPat.setTransferHandler(null);
        txtAMat.setTransferHandler(null);
        jPass.setTransferHandler(null);
        jPassConfirm.setTransferHandler(null);
    }

    /**
     * Metodos creados
     */
    public void lanzarRegistro() {
        try {
            LeerInicio leer = new LeerInicio();
            if (leer.getUsuariosAdmin()) {
                lblRegistrarse.setVisible(false);
            } else {
                lblRegistrarse.setVisible(true);
            }
        } catch (SQLException ex) {
            System.out.println("Error al conectar a la base de datos Inicio.java lanzarRegistro: " + ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dialogUsuario = new javax.swing.JDialog();
        dialogBackground = new javax.swing.JPanel();
        dlgInstrucciones = new javax.swing.JLabel();
        dlgNombre = new javax.swing.JLabel();
        dlgApPat = new javax.swing.JLabel();
        dlgApMat = new javax.swing.JLabel();
        dlgCont = new javax.swing.JLabel();
        dlgConfCont = new javax.swing.JLabel();
        barraSeparadora = new javax.swing.JPanel();
        txtNom = new javax.swing.JTextField();
        barraSeparadora1 = new javax.swing.JPanel();
        txtAPat = new javax.swing.JTextField();
        barraSeparadora2 = new javax.swing.JPanel();
        txtAMat = new javax.swing.JTextField();
        barraSeparadora4 = new javax.swing.JPanel();
        jPass = new javax.swing.JPasswordField();
        barraSeparadora5 = new javax.swing.JPanel();
        jPassConfirm = new javax.swing.JPasswordField();
        btnCrearUsuario = new javax.swing.JPanel();
        lblBtnCrear = new javax.swing.JLabel();
        pnlUsuario = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JLabel();
        pnlCabeceraVentana = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxAcceso = new javax.swing.JCheckBox();
        dialogAcceso = new javax.swing.JPanel();
        dlgAcceso = new javax.swing.JLabel();
        txtAcceso = new javax.swing.JTextField();
        recovery = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnRecov = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dlgManualContacto = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnContacto = new javax.swing.JPanel();
        lblIco = new javax.swing.JLabel();
        lblContacto = new javax.swing.JLabel();
        btnManual = new javax.swing.JPanel();
        lblIco1 = new javax.swing.JLabel();
        lblManual = new javax.swing.JLabel();
        dlgContacto = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        frameBackground = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        barraSeparadora6 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JPanel();
        lblBtnIniciar = new javax.swing.JLabel();
        lblIcoIniciar = new javax.swing.JLabel();
        lblInstruccionesAcceso = new javax.swing.JLabel();
        barraSeparadora7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPassAcceso = new javax.swing.JPasswordField();
        lblInstrucciones = new javax.swing.JLabel();
        lblIcoInstruccion = new javax.swing.JLabel();
        lblRegistrarse = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        recuperaPass = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        dialogUsuario.setLocation(new java.awt.Point(0, 0));
        dialogUsuario.setMinimumSize(new java.awt.Dimension(560, 628));
        dialogUsuario.setModal(true);
        dialogUsuario.setUndecorated(true);
        dialogUsuario.setResizable(false);

        dialogBackground.setBackground(new java.awt.Color(0, 173, 69));
        dialogBackground.setMinimumSize(new java.awt.Dimension(560, 628));
        dialogBackground.setPreferredSize(new java.awt.Dimension(560, 628));
        dialogBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dlgInstrucciones.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        dlgInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        dlgInstrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dlgInstrucciones.setText("<html><center>Esta ventana solo creara un usuario administrador<br>lea el manual para aprender a agregrar mas usuarios<center></html>");
        dialogBackground.add(dlgInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, -1));

        dlgNombre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dlgNombre.setForeground(new java.awt.Color(255, 255, 255));
        dlgNombre.setText("Nombre");
        dialogBackground.add(dlgNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        dlgApPat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dlgApPat.setForeground(new java.awt.Color(255, 255, 255));
        dlgApPat.setText("Apellido Paterno");
        dialogBackground.add(dlgApPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        dlgApMat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dlgApMat.setForeground(new java.awt.Color(255, 255, 255));
        dlgApMat.setText("Apellido Materno");
        dialogBackground.add(dlgApMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        dlgCont.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dlgCont.setForeground(new java.awt.Color(255, 255, 255));
        dlgCont.setText("Contraseña");
        dialogBackground.add(dlgCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        dlgConfCont.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dlgConfCont.setForeground(new java.awt.Color(255, 255, 255));
        dlgConfCont.setText("Confirmar contraseña");
        dialogBackground.add(dlgConfCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        barraSeparadora.setBackground(new java.awt.Color(255, 255, 255));
        barraSeparadora.setPreferredSize(new java.awt.Dimension(210, 3));

        javax.swing.GroupLayout barraSeparadoraLayout = new javax.swing.GroupLayout(barraSeparadora);
        barraSeparadora.setLayout(barraSeparadoraLayout);
        barraSeparadoraLayout.setHorizontalGroup(
            barraSeparadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadoraLayout.setVerticalGroup(
            barraSeparadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        dialogBackground.add(barraSeparadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        txtNom.setBackground(new java.awt.Color(0, 173, 69));
        txtNom.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNom.setForeground(new java.awt.Color(255, 255, 255));
        txtNom.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        txtNom.setPreferredSize(new java.awt.Dimension(210, 31));
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomKeyTyped(evt);
            }
        });
        dialogBackground.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        barraSeparadora1.setBackground(new java.awt.Color(255, 255, 255));
        barraSeparadora1.setPreferredSize(new java.awt.Dimension(210, 3));

        javax.swing.GroupLayout barraSeparadora1Layout = new javax.swing.GroupLayout(barraSeparadora1);
        barraSeparadora1.setLayout(barraSeparadora1Layout);
        barraSeparadora1Layout.setHorizontalGroup(
            barraSeparadora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadora1Layout.setVerticalGroup(
            barraSeparadora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        dialogBackground.add(barraSeparadora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        txtAPat.setBackground(new java.awt.Color(0, 173, 69));
        txtAPat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtAPat.setForeground(new java.awt.Color(255, 255, 255));
        txtAPat.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        txtAPat.setPreferredSize(new java.awt.Dimension(210, 31));
        txtAPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAPatKeyTyped(evt);
            }
        });
        dialogBackground.add(txtAPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        barraSeparadora2.setBackground(new java.awt.Color(255, 255, 255));
        barraSeparadora2.setPreferredSize(new java.awt.Dimension(210, 3));

        javax.swing.GroupLayout barraSeparadora2Layout = new javax.swing.GroupLayout(barraSeparadora2);
        barraSeparadora2.setLayout(barraSeparadora2Layout);
        barraSeparadora2Layout.setHorizontalGroup(
            barraSeparadora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadora2Layout.setVerticalGroup(
            barraSeparadora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        dialogBackground.add(barraSeparadora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        txtAMat.setBackground(new java.awt.Color(0, 173, 69));
        txtAMat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtAMat.setForeground(new java.awt.Color(255, 255, 255));
        txtAMat.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        txtAMat.setPreferredSize(new java.awt.Dimension(210, 31));
        txtAMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAMatKeyTyped(evt);
            }
        });
        dialogBackground.add(txtAMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        barraSeparadora4.setBackground(new java.awt.Color(255, 255, 255));
        barraSeparadora4.setPreferredSize(new java.awt.Dimension(210, 3));

        javax.swing.GroupLayout barraSeparadora4Layout = new javax.swing.GroupLayout(barraSeparadora4);
        barraSeparadora4.setLayout(barraSeparadora4Layout);
        barraSeparadora4Layout.setHorizontalGroup(
            barraSeparadora4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadora4Layout.setVerticalGroup(
            barraSeparadora4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        dialogBackground.add(barraSeparadora4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jPass.setBackground(new java.awt.Color(0, 173, 69));
        jPass.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPass.setForeground(new java.awt.Color(255, 255, 255));
        jPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        jPass.setPreferredSize(new java.awt.Dimension(210, 31));
        jPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassKeyTyped(evt);
            }
        });
        dialogBackground.add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        barraSeparadora5.setBackground(new java.awt.Color(255, 255, 255));
        barraSeparadora5.setPreferredSize(new java.awt.Dimension(210, 3));

        javax.swing.GroupLayout barraSeparadora5Layout = new javax.swing.GroupLayout(barraSeparadora5);
        barraSeparadora5.setLayout(barraSeparadora5Layout);
        barraSeparadora5Layout.setHorizontalGroup(
            barraSeparadora5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadora5Layout.setVerticalGroup(
            barraSeparadora5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        dialogBackground.add(barraSeparadora5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jPassConfirm.setBackground(new java.awt.Color(0, 173, 69));
        jPassConfirm.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPassConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jPassConfirm.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        jPassConfirm.setPreferredSize(new java.awt.Dimension(210, 31));
        jPassConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassConfirmKeyTyped(evt);
            }
        });
        dialogBackground.add(jPassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        btnCrearUsuario.setBackground(new java.awt.Color(239, 239, 239));
        btnCrearUsuario.setForeground(new java.awt.Color(100, 100, 100));
        btnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseExited(evt);
            }
        });

        lblBtnCrear.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblBtnCrear.setForeground(new java.awt.Color(100, 100, 100));
        lblBtnCrear.setText("Crear Usuario");

        javax.swing.GroupLayout btnCrearUsuarioLayout = new javax.swing.GroupLayout(btnCrearUsuario);
        btnCrearUsuario.setLayout(btnCrearUsuarioLayout);
        btnCrearUsuarioLayout.setHorizontalGroup(
            btnCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblBtnCrear)
                .addGap(23, 23, 23))
        );
        btnCrearUsuarioLayout.setVerticalGroup(
            btnCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearUsuarioLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblBtnCrear)
                .addGap(13, 13, 13))
        );

        dialogBackground.add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        pnlUsuario.setBackground(new java.awt.Color(154, 205, 50));
        pnlUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlUsuario.setMinimumSize(new java.awt.Dimension(560, 30));
        pnlUsuario.setPreferredSize(new java.awt.Dimension(560, 30));
        pnlUsuario.setLayout(new java.awt.GridBagLayout());

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_22px.png"))); // NOI18N
        btnCerrar.setPreferredSize(new java.awt.Dimension(23, 23));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 2, 0);
        pnlUsuario.add(btnCerrar, gridBagConstraints);

        pnlCabeceraVentana.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        pnlCabeceraVentana.setForeground(new java.awt.Color(255, 255, 255));
        pnlCabeceraVentana.setText("Crear Usuario Administrador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 165, 2, 119);
        pnlUsuario.add(pnlCabeceraVentana, gridBagConstraints);

        dialogBackground.add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/More Info_22px.png"))); // NOI18N
        dialogBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, 30));

        jCheckBoxAcceso.setBackground(new java.awt.Color(0, 173, 69));
        jCheckBoxAcceso.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBoxAcceso.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxAcceso.setText("Usar una credencial existente?");
        jCheckBoxAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAccesoActionPerformed(evt);
            }
        });
        dialogBackground.add(jCheckBoxAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        dialogAcceso.setBackground(new java.awt.Color(206, 210, 72));

        dlgAcceso.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        dlgAcceso.setText("Debe escanear la credencial que desea usar");

        txtAcceso.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txtAcceso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAcceso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 173, 179)));
        txtAcceso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccesoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout dialogAccesoLayout = new javax.swing.GroupLayout(dialogAcceso);
        dialogAcceso.setLayout(dialogAccesoLayout);
        dialogAccesoLayout.setHorizontalGroup(
            dialogAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(dialogAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogAccesoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(dialogAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(dialogAccesoLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(dlgAcceso)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogAccesoLayout.setVerticalGroup(
            dialogAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(dialogAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogAccesoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(dlgAcceso)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dialogBackground.add(dialogAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 500, 80));

        javax.swing.GroupLayout dialogUsuarioLayout = new javax.swing.GroupLayout(dialogUsuario.getContentPane());
        dialogUsuario.getContentPane().setLayout(dialogUsuarioLayout);
        dialogUsuarioLayout.setHorizontalGroup(
            dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogUsuarioLayout.setVerticalGroup(
            dialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogUsuario.getAccessibleContext().setAccessibleParent(this);

        recovery.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        recovery.setTitle("[Actualizar Password]");
        recovery.setMinimumSize(new java.awt.Dimension(325, 230));
        recovery.setModal(true);
        recovery.setResizable(false);

        jPasswordField1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setMinimumSize(new java.awt.Dimension(6, 22));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });

        btnRecov.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnRecov.setText("Guardar");
        btnRecov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecovActionPerformed(evt);
            }
        });

        jPasswordField2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyTyped(evt);
            }
        });

        jLabel3.setText("Contraseña nueva");

        jLabel4.setText("Clave");

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnRecov)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecov)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout recoveryLayout = new javax.swing.GroupLayout(recovery.getContentPane());
        recovery.getContentPane().setLayout(recoveryLayout);
        recoveryLayout.setHorizontalGroup(
            recoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        recoveryLayout.setVerticalGroup(
            recoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgManualContacto.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgManualContacto.setMinimumSize(new java.awt.Dimension(570, 250));
        dlgManualContacto.setModal(true);

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eliga una opción:");

        btnContacto.setBackground(new java.awt.Color(239, 239, 239));
        btnContacto.setMinimumSize(new java.awt.Dimension(105, 101));
        btnContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContactoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContactoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContactoMouseExited(evt);
            }
        });

        lblIco.setForeground(new java.awt.Color(255, 255, 255));
        lblIco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contact-70.png"))); // NOI18N
        lblIco.setToolTipText("da clic sobre mi");
        lblIco.setPreferredSize(new java.awt.Dimension(85, 70));
        lblIco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIcoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIcoMouseExited(evt);
            }
        });

        lblContacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContacto.setText("Contacto");

        javax.swing.GroupLayout btnContactoLayout = new javax.swing.GroupLayout(btnContacto);
        btnContacto.setLayout(btnContactoLayout);
        btnContactoLayout.setHorizontalGroup(
            btnContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIco, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        btnContactoLayout.setVerticalGroup(
            btnContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnContactoLayout.createSequentialGroup()
                .addComponent(lblIco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContacto)
                .addGap(11, 11, 11))
        );

        btnManual.setBackground(new java.awt.Color(239, 239, 239));
        btnManual.setMinimumSize(new java.awt.Dimension(105, 101));
        btnManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManualMouseExited(evt);
            }
        });

        lblIco1.setForeground(new java.awt.Color(255, 255, 255));
        lblIco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manual-70.png"))); // NOI18N
        lblIco1.setToolTipText("da clic sobre mi");
        lblIco1.setPreferredSize(new java.awt.Dimension(85, 70));
        lblIco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIco1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIco1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIco1MouseExited(evt);
            }
        });

        lblManual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManual.setText("Manual");

        javax.swing.GroupLayout btnManualLayout = new javax.swing.GroupLayout(btnManual);
        btnManual.setLayout(btnManualLayout);
        btnManualLayout.setHorizontalGroup(
            btnManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIco1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        btnManualLayout.setVerticalGroup(
            btnManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManualLayout.createSequentialGroup()
                .addComponent(lblIco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManual)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(btnContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgManualContactoLayout = new javax.swing.GroupLayout(dlgManualContacto.getContentPane());
        dlgManualContacto.getContentPane().setLayout(dlgManualContactoLayout);
        dlgManualContactoLayout.setHorizontalGroup(
            dlgManualContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgManualContactoLayout.setVerticalGroup(
            dlgManualContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dlgContacto.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgContacto.setTitle("[Contacto]");
        dlgContacto.setMinimumSize(new java.awt.Dimension(450, 350));
        dlgContacto.setModal(true);

        jPanel4.setBackground(new java.awt.Color(255, 152, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Creado por:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 33));

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Gómez Sotelo Juan Jesús");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Correos:");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 152, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("GomezSoteloJuan@gmail.com");
        jTextField1.setBorder(null);
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 30));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 152, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("10orangeblue@gmail.com");
        jTextField2.setBorder(null);
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 30));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/email-60.png"))); // NOI18N
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 60, 60));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/niceGuy-60.png"))); // NOI18N
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html>GitHub:<br><a href=\"https://github.com/ZSoJes/ApartarLiberarProy\">Link del Proyecto</a>");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 40));

        javax.swing.GroupLayout dlgContactoLayout = new javax.swing.GroupLayout(dlgContacto.getContentPane());
        dlgContacto.getContentPane().setLayout(dlgContactoLayout);
        dlgContactoLayout.setHorizontalGroup(
            dlgContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        dlgContactoLayout.setVerticalGroup(
            dlgContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Administrador de Video Proyectores");
        setIconImage(img.getImage());
        setResizable(false);

        frameBackground.setBackground(new java.awt.Color(18, 182, 18));
        frameBackground.setMinimumSize(new java.awt.Dimension(960, 520));
        frameBackground.setPreferredSize(new java.awt.Dimension(960, 520));
        frameBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setMinimumSize(new java.awt.Dimension(490, 230));
        login.setPreferredSize(new java.awt.Dimension(490, 230));
        login.setLayout(new java.awt.GridBagLayout());

        txtUsuario.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 2, 3, 2));
        txtUsuario.setMinimumSize(new java.awt.Dimension(270, 35));
        txtUsuario.setPreferredSize(new java.awt.Dimension(270, 35));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        login.add(txtUsuario, gridBagConstraints);

        barraSeparadora6.setBackground(new java.awt.Color(107, 107, 107));
        barraSeparadora6.setMinimumSize(new java.awt.Dimension(270, 3));
        barraSeparadora6.setPreferredSize(new java.awt.Dimension(270, 3));

        javax.swing.GroupLayout barraSeparadora6Layout = new javax.swing.GroupLayout(barraSeparadora6);
        barraSeparadora6.setLayout(barraSeparadora6Layout);
        barraSeparadora6Layout.setHorizontalGroup(
            barraSeparadora6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadora6Layout.setVerticalGroup(
            barraSeparadora6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        login.add(barraSeparadora6, gridBagConstraints);

        btnIniciar.setBackground(new java.awt.Color(0, 178, 104));
        btnIniciar.setMinimumSize(new java.awt.Dimension(159, 46));
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarMouseExited(evt);
            }
        });

        lblBtnIniciar.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        lblBtnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        lblBtnIniciar.setText("Iniciar");

        lblIcoIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Home24px.png"))); // NOI18N

        javax.swing.GroupLayout btnIniciarLayout = new javax.swing.GroupLayout(btnIniciar);
        btnIniciar.setLayout(btnIniciarLayout);
        btnIniciarLayout.setHorizontalGroup(
            btnIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIniciarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblIcoIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBtnIniciar)
                .addGap(29, 29, 29))
        );
        btnIniciarLayout.setVerticalGroup(
            btnIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnIniciarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIcoIniciar)
                    .addComponent(lblBtnIniciar))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        login.add(btnIniciar, gridBagConstraints);

        lblInstruccionesAcceso.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblInstruccionesAcceso.setForeground(new java.awt.Color(100, 100, 100));
        lblInstruccionesAcceso.setText("El acceso se realiza al escanear la credencial de uno de lo administradores");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 30, 0, 30);
        login.add(lblInstruccionesAcceso, gridBagConstraints);

        barraSeparadora7.setBackground(new java.awt.Color(107, 107, 107));
        barraSeparadora7.setMinimumSize(new java.awt.Dimension(230, 2));
        barraSeparadora7.setPreferredSize(new java.awt.Dimension(230, 2));

        javax.swing.GroupLayout barraSeparadora7Layout = new javax.swing.GroupLayout(barraSeparadora7);
        barraSeparadora7.setLayout(barraSeparadora7Layout);
        barraSeparadora7Layout.setHorizontalGroup(
            barraSeparadora7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barraSeparadora7Layout.setVerticalGroup(
            barraSeparadora7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        login.add(barraSeparadora7, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(100, 100, 100));
        jLabel2.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        login.add(jLabel2, gridBagConstraints);

        jPassAcceso.setFont(new java.awt.Font("SansSerif", 0, 21)); // NOI18N
        jPassAcceso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPassAcceso.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        jPassAcceso.setMinimumSize(new java.awt.Dimension(230, 35));
        jPassAcceso.setPreferredSize(new java.awt.Dimension(230, 35));
        jPassAcceso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassAccesoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 0);
        login.add(jPassAcceso, gridBagConstraints);

        frameBackground.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        lblInstrucciones.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        lblInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        lblInstrucciones.setText("Solo los administradores pueden brindar acceso al sistema");
        frameBackground.add(lblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, 20));

        lblIcoInstruccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/More Info_22px.png"))); // NOI18N
        frameBackground.add(lblIcoInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        lblRegistrarse.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarse.setText("Registrarse");
        lblRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseExited(evt);
            }
        });
        frameBackground.add(lblRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        lblTexto.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setText("Inciar Sesión");
        frameBackground.add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        lblTexto.getAccessibleContext().setAccessibleName("Iniciar Sesion");

        recuperaPass.setBackground(new java.awt.Color(18, 182, 18));
        recuperaPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recuperaPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout recuperaPassLayout = new javax.swing.GroupLayout(recuperaPass);
        recuperaPass.setLayout(recuperaPassLayout);
        recuperaPassLayout.setHorizontalGroup(
            recuperaPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        recuperaPassLayout.setVerticalGroup(
            recuperaPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        frameBackground.add(recuperaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 20, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/question-28.png"))); // NOI18N
        jLabel5.setToolTipText("da clic sobre mi");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        frameBackground.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseEntered
        lblRegistrarse.setForeground(new Color(255, 85, 85));
    }//GEN-LAST:event_lblRegistrarseMouseEntered

    private void lblRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseClicked
        dialogUsuario.setLocationRelativeTo(frameBackground);
        dialogUsuario.setVisible(true);
        lblRegistrarse.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblRegistrarseMouseClicked

    private void lblRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseExited
        lblRegistrarse.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblRegistrarseMouseExited

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        if (txtUsuario.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void btnCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseClicked
        btnCrearUsuario.setBackground(new Color(239,239,239));
        lblBtnCrear.setForeground(new Color(100, 100, 100));

        String nom = txtNom.getText().trim().toUpperCase();
        String apat = txtAPat.getText().trim().toUpperCase();
        String amat = txtAMat.getText().trim().toUpperCase();
        char[] pass = jPass.getPassword();
        char[] passC = jPassConfirm.getPassword();
        String cred = txtAcceso.getText().trim();
        
        //revisar las contraseñas no esten en blanco
        if (!String.valueOf(pass).trim().isEmpty() && !String.valueOf(passC).trim().isEmpty()) {
            if (pass.length >= 8 ){
                
            
            //revisar ambas contraseñas sean iguales
            if (Arrays.equals(pass, passC)) {
                //revisar los cuadros de texto no esten en blanco
                if (!nom.isEmpty() && !(apat.length() < 2) && !amat.isEmpty()) {
                    try {
                        CrearInicio crear = new CrearInicio();
                        String hashed = BCrypt.hashpw(String.valueOf(pass).trim(), BCrypt.gensalt(12));  //cifrado
                        String datos[] = {nom, apat, amat, hashed};      // asigna para el metodo setUsuario
                        //revisar si el checkbox fue seleccionado
                        if (jCheckBoxAcceso.isSelected()) {
                            //revisar si el cuadro de acceso no esta en blanco
                            if (!cred.isEmpty()) {
                                System.out.println("id:" + cred);
                                crear.setUsuario(datos, true, cred);
                                GenerarReportes g = new GenerarReportes();
                                g.credencialUsuario(cred);
                                
                                lanzarRegistro();

                                //CERRAR DIALOG
                                dialogUsuario.setVisible(false);
                                dialogUsuario.dispose();
                            } else {
                                txtAcceso.setText("");
                                JOptionPane.showMessageDialog(null, "Desmarque la casilla anterior\nsi no desea usar una credencial existente", "Información", JOptionPane.INFORMATION_MESSAGE);
                            }
                        } else {
                            String id = crear.setUsuario(datos, true);
                            if(!id.isEmpty()){
                                System.out.println("se va a generar credencial");
                                GenerarReportes g = new GenerarReportes();
                                g.credencialUsuario(id);
                                
                                lanzarRegistro();

                                //CERRAR DIALOG
                                dialogUsuario.setVisible(false);
                                dialogUsuario.dispose();
                            }
                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debe llenar completamente el formulario", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ambas contraseñas deben coincidir", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
            
            }else{
                JOptionPane.showMessageDialog(null, "La contraseña ideal:\nal menos 8 caracteres sin datos personales", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No puede dejar las contraseñas en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // cerrar ventana

        //LIMPIAR CUADROS DE TEXTO
        txtNom.setText("");
        txtAPat.setText("");
        txtAMat.setText("");
        jPass.setText("");
        jPassConfirm.setText("");
    }//GEN-LAST:event_btnCrearUsuarioMouseClicked

    
    private void btnCrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseEntered
        btnCrearUsuario.setBackground(new Color(255, 103, 96));
        lblBtnCrear.setForeground(Color.white);
    }//GEN-LAST:event_btnCrearUsuarioMouseEntered

    private void btnCrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseExited
        btnCrearUsuario.setBackground(new Color(239,239,239));
        lblBtnCrear.setForeground(new Color(100, 100, 100));
    }//GEN-LAST:event_btnCrearUsuarioMouseExited

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        dialogUsuario.setVisible(false);
        dialogUsuario.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        lblIcoIniciar.setIcon(homeW);
        lblBtnIniciar.setForeground(Color.white);
        darAcceso();
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void btnIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseEntered
        lblIcoIniciar.setIcon(homeB);
        lblBtnIniciar.setForeground(new Color(100, 100, 100));
    }//GEN-LAST:event_btnIniciarMouseEntered

    private void btnIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseExited
        lblIcoIniciar.setIcon(homeW);
        lblBtnIniciar.setForeground(Color.white);
    }//GEN-LAST:event_btnIniciarMouseExited

    private void jCheckBoxAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAccesoActionPerformed
        if (jCheckBoxAcceso.isSelected()) {
            dialogAcceso.setVisible(true);
        } else {
            dialogAcceso.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxAccesoActionPerformed

    private void txtAccesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccesoKeyTyped
        if (txtAcceso.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAccesoKeyTyped

    private void jPassAccesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassAccesoKeyTyped
        if (jPassAcceso.getPassword().length >= 12) {
            evt.consume();
        }
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            darAcceso();
        }
    }//GEN-LAST:event_jPassAccesoKeyTyped

    private void txtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyTyped
        limiteYcaracteres(txtNom, 25, evt);
    }//GEN-LAST:event_txtNomKeyTyped

    private void txtAPatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPatKeyTyped
        limiteYcaracteres(txtAPat, 15, evt);
    }//GEN-LAST:event_txtAPatKeyTyped

    private void txtAMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAMatKeyTyped
        limiteYcaracteres(txtAMat, 15, evt);
    }//GEN-LAST:event_txtAMatKeyTyped

    private void jPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassKeyTyped
        if (jPass.getPassword().length >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_jPassKeyTyped

    private void jPassConfirmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassConfirmKeyTyped
        if (jPassConfirm.getPassword().length >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_jPassConfirmKeyTyped

    private void recuperaPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuperaPassMouseClicked
        if (evt.getClickCount() == 3) {
            String usuario = txtUsuario.getText().trim();
            try{
                LeerInicio leer = new LeerInicio();    
                System.out.println("es admin:" + leer.getEsAdminUsuario(usuario));
                String[] usr = leer.getUsuario(usuario);
                if(usr[0] != null && leer.getEsAdminUsuario(usuario)){
                    int opc = JOptionPane.showConfirmDialog(null, "CONTRASEÑA:", "Info",JOptionPane.WARNING_MESSAGE,JOptionPane.YES_NO_OPTION);
                    if(opc == JOptionPane.OK_OPTION){
                        recovery.setLocationRelativeTo(frameBackground);
                        recovery.setVisible(true);
                    }
                }
            }catch(SQLException ex){
                    System.out.println("Error usuario recuperar pass: " + ex);
            }
        }    
    }//GEN-LAST:event_recuperaPassMouseClicked

    private void jPasswordField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyTyped
        char c = evt.getKeyChar();
        if( c == KeyEvent.VK_ENTER){
            btnRecov.doClick();
        }
        if (jPasswordField1.getPassword().length >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordField2KeyTyped

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        char c = evt.getKeyChar();
        if( c == KeyEvent.VK_ENTER){
            btnRecov.doClick();
        }
        if (jPasswordField1.getPassword().length >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void btnRecovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecovActionPerformed
        char[] pass1 = jPasswordField1.getPassword();
        char[] pass2 = jPasswordField2.getPassword();
        char[] intento = { '7','3','1','2','5','6','1','6'};
        if(!String.valueOf(pass1).isEmpty() & !String.valueOf(pass2).isEmpty()){
            if(Arrays.equals(pass1, intento)) {
                if (pass2.length >= 8) {
                    String usuario = txtUsuario.getText().trim();
                    String hashed = BCrypt.hashpw(String.valueOf(pass2).trim(), BCrypt.gensalt(12)); //cifrado
                    try {
                        LeerInicio leer = new LeerInicio();
                        leer.updUsuarioPass(usuario, hashed);
                        JOptionPane.showMessageDialog(null, "La contraseña se ha actualizado!!!", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                        recovery.setVisible(false);
                        recovery.dispose();
                        jPasswordField1.setText("");
                        jPasswordField2.setText("");
                    } catch (SQLException e) {
                        System.out.println("Error al actualizar: " + e);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "La contraseña debe ser de minimo 8 caracteres/numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                    JOptionPane.showMessageDialog(this, "Rectifique la clave", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    jPasswordField1.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(this, "no deje ningun campo en blanco", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRecovActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        recovery.setVisible(false);
        recovery.dispose();
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dlgManualContacto.setLocationRelativeTo(frameBackground);
        dlgManualContacto.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactoMouseClicked
        btnContacto.setBackground(new Color(239,239,239));
        dlgContacto.setLocationRelativeTo(this);
        dlgContacto.setVisible(true);
    }//GEN-LAST:event_btnContactoMouseClicked

    private void btnContactoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactoMouseEntered
        btnContacto.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnContactoMouseEntered

    private void btnContactoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactoMouseExited
        btnContacto.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_btnContactoMouseExited

    private void btnManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualMouseClicked
        btnManual.setBackground(new Color(239,239,239));
        dlgManualContacto.setVisible(false);
        dlgManualContacto.dispose();
        abrirManual();
    }//GEN-LAST:event_btnManualMouseClicked

    private void btnManualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualMouseEntered
        btnManual.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnManualMouseEntered

    private void btnManualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManualMouseExited
        btnManual.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_btnManualMouseExited

    private void lblIco1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIco1MouseClicked
        btnManual.setBackground(new Color(239,239,239));
        dlgManualContacto.setVisible(false);
        dlgManualContacto.dispose();
        abrirManual();
    }//GEN-LAST:event_lblIco1MouseClicked

    private void lblIco1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIco1MouseEntered
        btnManual.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblIco1MouseEntered

    private void lblIco1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIco1MouseExited
        btnManual.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_lblIco1MouseExited

    private void lblIcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoMouseClicked
        btnContacto.setBackground(new Color(239,239,239));
        dlgContacto.setLocationRelativeTo(this);
        dlgContacto.setVisible(true);
    }//GEN-LAST:event_lblIcoMouseClicked

    private void lblIcoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoMouseEntered
        btnContacto.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblIcoMouseEntered

    private void lblIcoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoMouseExited
        btnContacto.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_lblIcoMouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://github.com/ZSoJes/ApartarLiberarProy"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    public void abrirManual(){
        try {
            File path = new File ("./src/manual.pdf");
            Desktop.getDesktop().open(path);
       }catch (IOException ex) {
            ex.printStackTrace();
       }
    }
    public void darAcceso(){
        String usuario = txtUsuario.getText().trim();
        try {
            LeerInicio leer = new LeerInicio();
            try {
                if (leer.getExisteUsuario(usuario)) {
                    String hashed = leer.getPass(usuario);
                    if (BCrypt.checkpw(String.valueOf(jPassAcceso.getPassword()), hashed)) {
                        if(leer.getEsAdminUsuario(usuario)){
                            Menu menu = new Menu();
                            menu.setVisible(true);
                            this.setVisible(false);
                            this.dispose();
                            System.out.println("\nAcceso valido...\n\n");
                        }else{
                            throw new Exception();
                        }
                    } else {
                        throw new Exception();
                    }
                } else {
                    throw new Exception();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Intenta de nuevo\nEsta ingresando icorrectamente \nusuario y/o contraseña!!!\n\no su usuario no puede dar inicio al programa", "Error", JOptionPane.ERROR_MESSAGE);
                txtUsuario.setText("");
                jPassAcceso.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void limiteYcaracteres(JTextField nombre, int limite, java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar(); //probar introducir solo caracteres
        String cad = ("" + c).toUpperCase();
        c = cad.charAt(0);
        evt.setKeyChar(c);
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
        if (nombre.getText().length() >= limite) {
            evt.consume();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Inicio().setVisible(true);
            } catch (SQLException ex) {
                System.out.println("Error de sql en main: " + ex);
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSeparadora;
    private javax.swing.JPanel barraSeparadora1;
    private javax.swing.JPanel barraSeparadora2;
    private javax.swing.JPanel barraSeparadora4;
    private javax.swing.JPanel barraSeparadora5;
    private javax.swing.JPanel barraSeparadora6;
    private javax.swing.JPanel barraSeparadora7;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JPanel btnContacto;
    private javax.swing.JPanel btnCrearUsuario;
    private javax.swing.JPanel btnIniciar;
    private javax.swing.JPanel btnManual;
    private javax.swing.JButton btnRecov;
    private javax.swing.JPanel dialogAcceso;
    private javax.swing.JPanel dialogBackground;
    private javax.swing.JDialog dialogUsuario;
    private javax.swing.JLabel dlgAcceso;
    private javax.swing.JLabel dlgApMat;
    private javax.swing.JLabel dlgApPat;
    private javax.swing.JLabel dlgConfCont;
    private javax.swing.JLabel dlgCont;
    private javax.swing.JDialog dlgContacto;
    private javax.swing.JLabel dlgInstrucciones;
    private javax.swing.JDialog dlgManualContacto;
    private javax.swing.JLabel dlgNombre;
    private javax.swing.JPanel frameBackground;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxAcceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JPasswordField jPassAcceso;
    private javax.swing.JPasswordField jPassConfirm;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblBtnCrear;
    private javax.swing.JLabel lblBtnIniciar;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblIco;
    private javax.swing.JLabel lblIco1;
    private javax.swing.JLabel lblIcoIniciar;
    private javax.swing.JLabel lblIcoInstruccion;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblInstruccionesAcceso;
    private javax.swing.JLabel lblManual;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JPanel login;
    private javax.swing.JLabel pnlCabeceraVentana;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JDialog recovery;
    private javax.swing.JPanel recuperaPass;
    private javax.swing.JTextField txtAMat;
    private javax.swing.JTextField txtAPat;
    private javax.swing.JTextField txtAcceso;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
